---

- block:

    - name: "Release ROM for {{ BDEVICE }}"
      shell: "scp {{ JKZIPDIR }}/{{ item }} {{ groups.downloadserver[0] }}:{{ rempath }}"
      delegate_to: "{{ groups.buildserver[0] }}"
      loop:
        - "{{ ROMFILE.stdout }}"
        - "{{ ROMFILE.stdout }}.sha*sum"

    - name: "Correct ZIP timestamp for {{ BDEVICE }} to fix recurring OTA offering"
      file:
        path: "{{ rempath }}/{{ ROMFILE.stdout }}"
        modification_time: "{{ "%Y%m%d%H%M.%S" | strftime(build_date_utc) }}"
        access_time: "{{ "%Y%m%d%H%M.%S" | strftime(build_date_utc) }}"
        state: touch
      delegate_to: "{{ groups.downloadserver[0] }}"
  
  when:
    - ROM_FLAVOR != "TWRP"
    - ROM_FLAVOR != "SHRP"
    - ROM_FLAVOR != "MAID"
    - axp_build_recovery_only is undefined or (axp_build_recovery_only is defined and not axp_build_recovery_only)

- name: "Release RECOVERY for {{ BDEVICE }}"
  shell: "scp {{ JKZIPDIR }}/{{ item }} {{ groups.downloadserver[0] }}:{{ rempath }}"
  delegate_to: "{{ groups.buildserver[0] }}"
  loop:
    - "{{ ROMFILE.stdout }}"
    - "{{ ROMFILE.stdout }}.sha256sum"
  when:
    - ROM_FLAVOR == "TWRP" or ROM_FLAVOR == "SHRP" or (axp_build_recovery_only is defined and axp_build_recovery_only)
