---

#MAID_TYPE: "{{ RELEASE_TYPE }}"
#REPO_UPLOAD_PKG_USER: "{{ vault_buildmaidserver_user }}"
#REPO_UPLOAD_PKG_PATH: "/home/nightlies/roms/mAid/.repo/"
#REPO_UPLOAD_ISO_SRV: "{{ REPO_UPLOAD_PKG_SRV }}"
#REPO_UPLOAD_ISO_USER: "{{ REPO_UPLOAD_PKG_USER }}"
#REPO_UPLOAD_ISO_PATH: "/home/nightlies/roms/mAid/"

REPO_UPLOAD_PKG_SRV: "{{ groups.downloadserver[0] }}"
REPO_UPLOAD_ISO_SRV: "{{ REPO_UPLOAD_PKG_SRV }}"
RELEASE_TYPE: nightly

repo_mAid_http: "https://code.binbash.rocks:8443/mAid/build.git"
maid_home_path: "build_maid"
SRCPATH: "{{ maid_home_path }}"
maid_build_path: "/var/tmp"

# default mAid kernel if not specified in Semaphore
maid_kernel: linux515

# default build vars
debug_build: 'false'
skip_clean_build: 'false'
