---

- include_tasks: ../../common/tasks/setvars.yml
- include_tasks: ../../common/tasks/clean.yml
- include_tasks: ../../common/tasks/sync.yml
  when:
    - (override_reset_git == "undef" and reset_git == "true") or (override_reset_git == "true") or (override_sync == "true")

- include_tasks: patch.yml
  when: 
    - (override_reset_git == "undef" and reset_git == "true") or (override_reset_git == "true") or (force_patch is defined and force_patch == "true")

- include_tasks: copy.yml
