---

- name: "Get all available patches"
  find:
    paths: "{{ SRCPATH }}/external/patches"
    patterns: "*.diff"
  register: patch

- name: "Apply patches"
  shell: "git apply external/patches/{{ item }}"
  args:
    chdir: "{{ SRCPATH }}"
  loop: "{{ patch.files }}"
  when: patch.examined > 0
