---
# dynamic variables based on given pipeline vars

- set_fact:
    dtree_cl: "\\- Device tree: [commits](https://github.com/sfX-android/android_device_oneplus_hotdog/commits/eos-q_lockedbl)\n"
    cdtree_cl: "\\- Common tree: [commits](https://github.com/sfX-android/android_device_oneplus_sm8150-common/commits/eos-q_lockedbl)"
  connection: local
  when: EOS_RELEASE_TYPE == "CUSTOM"

- set_fact:
    dtree_cl: "\\- Device tree: [commits](https://github.com/sfX-android/android_device_oneplus_hotdog/commits/eos-q)\n"
    cdtree_cl: "\\- Common tree: [commits](https://github.com/sfX-android/android_device_oneplus_sm8150-common/commits/eos-q)"
  connection: local
  when: EOS_RELEASE_TYPE != "CUSTOM"

- set_fact:
    device_cl: |-
        ***{{ target_model_full }}*** ***\({{ target_model | replace("-","\-") | replace("_","\_") }}\)*** \- ***{{ ROM_FLAVOR | replace("-","\-") }} {{ git_repo_main_branch | replace("-","\-") | replace(".","\.") }}*** \(signed, ROOTED\)
    dl_links: |-
        ***Download:*** [{{ BUILDIDENT }} \- rooted]({{ leech_server }}/e-os/a10_rooted/{{ target_model }})
    keysdir: '/home/androidsource/do-not-touch/KEYS/{{ ROM_FLAVOR }}-{{ android_shortversion }}_{{ target_model }}_rooted'
    rempath: "/home/nightlies/roms/e-os/a10_rooted/{{ target_model }}"
  connection: local
  when: PREROOT_BOOT == "true"

- set_fact:
    device_cl: |-
        ***{{ target_model_full }}*** ***\({{ target_model | replace("-","\-") | replace("_","\_") }}\)*** \- ***{{ ROM_FLAVOR | replace("-","\-") }} {{ git_repo_main_branch | replace("-","\-") | replace(".","\.") }}*** \(signed, NO root\)
    keysdir: '/home/androidsource/do-not-touch/KEYS/{{ ROM_FLAVOR }}-{{ android_shortversion }}_{{ target_model }}'
    rempath: "/home/nightlies/roms/e-os/a10/{{ target_model }}/"
  connection: local
  when: PREROOT_BOOT != "true"
