---

- include_tasks: ../../../common/tasks/clean.yml
  vars:
    override_reset_git: 'true'

- name: "Specific DOS -basic- cleanup"
  file:
    path: "{{ item }}"
    state: absent
  loop:
    - "{{ SRCPATH }}/out/target/product/{{ target_model }}/rec_tmp"

- name: "Specific DOS -full- cleanup"
  file:
    path: "{{ item }}"
    state: absent
  loop:
    - "{{ SRCPATH }}/DOS_PATCHED_FLAG"
    - "{{ SRCPATH }}/packages/apps/Fennec_DOS-Shim"
    - "{{ SRCPATH }}/vendor/divested"
    - "{{ SRCPATH }}/vendor/fdroid_prebuilt"
    - "{{ SRCPATH }}/packages/apps/SupportDivestOS"
  when: 
     - (override_reset_git == "undef" and reset_git == "true") or (override_reset_git == "true") or (override_sync == "true")

- name: "Specific AXP.OS -full- cleanup"
  shell: "find vendor/extendrom vendor/axp -name EXTENDROM_PATCHER_DONE -delete"
  args:
    chdir: "{{ SRCPATH }}"
  when: 
     - (override_reset_git == "undef" and reset_git == "true") or (override_reset_git == "true") or (override_sync == "true")
