---

- include: vars.yml
- include: clean.yml

- block:

  - include: sync.yml
  - include: selinux_permissive.yml
    when: 
      - axp_allow_permissive is defined and axp_allow_permissive | bool

  when:
    - (override_reset_git == "undef" and reset_git == "true") or (override_reset_git == "true") or (override_sync == "true")
