---

- include_tasks: prep.yml
- include_tasks: vars.yml
- include_tasks: clean.yml

- block:

  - include_tasks: sync.yml    
  - include_tasks: patch.yml
  - include_tasks: adjust_DOS_options.yml

  when:
    - (override_reset_git == "undef" and reset_git == "true") or (override_reset_git == "true") or (override_sync == "true")
