---

- include_tasks: prep.yml
- include_tasks: vars.yml
- include_tasks: clean.yml

- block:

  - include_tasks: sync.yml    
  - include_tasks: patch.yml
  
  - include_tasks: patch_device_gs201.yml
    when: 
      - target_model == "cheetah"
  
  - include_tasks: adjust_DOS_options.yml

  - name: "Push to AXP.OS org"
    include_tasks: git_push.yml
    when:
      - commit_push | d(False)
      - early_push | d(False)

  when:
    - (override_reset_git == "undef" and reset_git == "true") or (override_reset_git == "true") or (override_sync == "true")
