---

- name: "disable GPG verify if dirty build"
  ansible.builtin.lineinfile:
    path: "{{ DOSPATH }}/Scripts/LineageOS-{{ los_version }}/Functions.sh"
    line: '#verifyAllPlatformTag'
    regexp: '\s+verifyAllPlatformTags\;'
  when:
    - clean_out != "true" or (override_clean_out != "true") or (skip_gpg_verify | bool)

- name: "apply DOS patches"
  raw: |
    {{ DOS_INIT }}
    patchWorkspace >> {{ BUILD_LOG }} 2>&1 \
      && awk -i inplace '!/enforce-product-packages-exist-internal/' vendor/lineage/config/common.mk
  register: patchout
  args:
    executable: /bin/bash

# AXP.OS adjustments (e.g wireguard, OTA,..)
- name: "apply AXP.OS adjustments"
  raw: |
    {{ DOS_INIT }}
    lunch lineage_{{ target_model }}-user && echo lunch success \
      && vendor/axp/axp.sh
  args:
    executable: /bin/bash

- name: "apply AXP.OS patches (common)"
  raw: |
      {{ DOS_INIT }}
      vendor/extendrom/tools/apply_patches.sh vendor/axp/patches/common
  args:
    executable: /bin/bash

- name: "apply AXP.OS patches (wireguard)"
  raw: |
      {{ DOS_INIT }}
      vendor/extendrom/tools/apply_patches.sh vendor/axp/patches/kernel \
        && cp -v kernel/wireguard-linux-compat/src/compat/compat.h {{ target_kernel_dir }}/net/wireguard/compat/
  args:
    executable: /bin/bash
  when: skip_wireguard is undefined or not skip_wireguard

