---

- name: "apply DOS patches"
  shell: |
    source ~/.bashrc
    source build/envsetup.sh  && echo "sourcing envsetup: success" \
      && source ../../Scripts/init.sh  && echo "sourcing init: success" \
      && patchWorkspace >> {{ BUILD_LOG }} 2>&1 \
      && awk -i inplace '!/enforce-product-packages-exist-internal/' vendor/lineage/config/common.mk
  register: patchout
  #failed_when: "'No error detected' not in patchout.stdout"
  environment:
    BDEVICE: "{{ target_model }}"
    PATH: "{{ BUILDHOME }}/.yarn/bin:{{ BUILDHOME }}/.config/yarn/global/node_modules/.bin:{{ BUILDHOME }}/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
  args:
    chdir: "{{ SRCPATH }}"
    executable: "/bin/bash"

# AXP.OS adjustments (e.g wireguard, OTA,..)
- name: "apply AXP.OS adjustments"
  shell: |
    source ~/.bashrc
    source build/envsetup.sh  && echo "sourcing envsetup: success" \
      && source ../../Scripts/init.sh  && echo "sourcing init: success" \
      && lunch lineage_{{ target_model }} \
      && vendor/axp/axp.sh
  environment:
    BDEVICE: "{{ target_model }}"
    PATH: "{{ BUILDHOME }}/.yarn/bin:{{ BUILDHOME }}/.config/yarn/global/node_modules/.bin:{{ BUILDHOME }}/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
  args:
    chdir: "{{ SRCPATH }}"
    executable: "/bin/bash"

- name: "revert to Lineage compatible OTA"
  shell: |
      patch -Rtp1 --no-backup-if-mismatch < {{ item.patch }} && echo "successfully reversed patch: {{ item.patch }}"
  args:
    chdir: "{{ item.patchpath }}"
    executable: "/bin/bash"
  loop:
    - { "patchpath": "{{ SRCPATH }}/packages/apps/Updater", "patch": "{{ DOSPATH }}/Patches/{{ git_repo_main_branch | replace('lineage','LineageOS') }}/android_packages_apps_Updater/0002-Tor_Support.patch" }
    - { "patchpath": "{{ SRCPATH }}/packages/apps/Updater", "patch": "{{ DOSPATH }}/Patches/{{ git_repo_main_branch | replace('lineage','LineageOS') }}/android_packages_apps_Updater/0001-Server.patch" }
