---

- name: "apply DOS patches"
  shell: |
    source ~/.bashrc
    source build/envsetup.sh  && echo "sourcing envsetup: success" \
      && source ../../Scripts/init.sh  && echo "sourcing init: success" \
      && patchWorkspace >> {{ BUILD_LOG }} 2>&1 \
      && awk -i inplace '!/enforce-product-packages-exist-internal/' vendor/lineage/config/common.mk
  register: patchout
  #failed_when: "'No error detected' not in patchout.stdout"
  environment:
    BDEVICE: "{{ target_model }}"
    PATH: "{{ BUILDHOME }}/.yarn/bin:{{ BUILDHOME }}/.config/yarn/global/node_modules/.bin:{{ BUILDHOME }}/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
  args:
    chdir: "{{ SRCPATH }}"
    executable: "/bin/bash"

# AXP.OS adjustments (e.g wireguard, OTA,..)
- name: "apply AXP.OS adjustments"
  shell: |
    source ~/.bashrc
    source build/envsetup.sh \
      && source ../../Scripts/init.sh \
      && lunch lineage_{{ target_model }}-user && echo lunch success \
      && vendor/axp/axp.sh
  environment:
    BDEVICE: "{{ target_model }}"
    PATH: "{{ BUILDHOME }}/.yarn/bin:{{ BUILDHOME }}/.config/yarn/global/node_modules/.bin:{{ BUILDHOME }}/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
  args:
    chdir: "{{ SRCPATH }}"
    executable: "/bin/bash"

- name: "apply AXP.OS patches"
  shell: |
      source ~/.bashrc
      source build/envsetup.sh \
        && source ../../Scripts/init.sh \
        && vendor/extendrom/tools/apply_patches.sh vendor/axp/patches
  args:
    chdir: "{{ SRCPATH }}"
    executable: "/bin/bash"

#- fail:
#    msg: boo
