---

- name: "disable GPG verify if dirty build"
  ansible.builtin.lineinfile:
    path: "{{ DOSPATH }}/Scripts/LineageOS-{{ los_version }}/Functions.sh"
    line: '#verifyAllPlatformTag'
    regexp: '\s+verifyAllPlatformTags\;'
  when:
    - clean_out != "true" or (override_clean_out != "true") or (skip_gpg_verify | bool)

- name: "disable wireguard handling by vendor/axp"
  file:
    path: "{{ SRCPATH }}/.wg.patched"
    state: touch
  when: skip_wireguard is defined and skip_wireguard | bool

- name: "apply DOS kernel patches (unsupported DOS devices)"
  raw: |
    {{ DOS_INIT }}
    CROOT="{{ SRCPATH }}"
    set +e
    cd {{ DOSPATH }}
    patch -r - --no-backup-if-mismatch --forward --ignore-whitespace --verbose -p1 < {{ BUILDHOME }}/cve_fixup.patch >> {{ BUILD_LOG }} 2>&1
    patch -r - --no-backup-if-mismatch --forward --ignore-whitespace --verbose -p1 < {{ BUILDHOME }}/getDefconfig.patch >> {{ BUILD_LOG }} 2>&1
    cd $CROOT
    startPatcher {{ target_kernel_dir | regex_replace('/','_') }} >> {{ BUILD_LOG }} 2>&1
    {{ repo_bin }} forall -j{{ max_processes }} {{ target_kernel_dir }} -c "git am --abort; git rebase --abort; git reset --hard" >> {{ BUILD_LOG }} 2>&1
    cd {{ DOSPATH }}/Scripts/LineageOS-{{ los_version }}/CVE_Patchers
    bash {{ DOSPATH }}/Scripts/Common/Fix_CVE_Patchers.sh >> {{ BUILD_LOG }} 2>&1
    cd $CROOT
    bash {{ DOSPATH }}/Scripts/LineageOS-{{ los_version }}/CVE_Patchers/android_{{ target_kernel_dir | regex_replace('/','_') }}.sh >> {{ BUILD_LOG }} 2>&1
  args:
    executable: /bin/bash
  when:
    - divest_unsupported_device
    - unsupported_device_kernel_patch | bool

- name: "apply DOS patches"
  raw: |
    {{ DOS_INIT }}
    patchWorkspaceReal >> {{ BUILD_LOG }} 2>&1 \
      && awk -i inplace '!/enforce-product-packages-exist-internal/' vendor/lineage/config/common.mk
  register: patchout
  args:
    executable: /bin/bash

- name: "overlay workaround for older Android"   
  shell: cp vendor/axp/overlays/packages/apps/SetupWizard/res/drawable/logo.xml vendor/divested/overlay/common/packages/apps/SetupWizard/res/drawable/logo.xml
  args:
    chdir: "{{ SRCPATH }}"
  when: android_shortversion == "a10" or android_shortversion == "a11"

# AXP.OS adjustments (e.g wireguard, OTA,..)
- name: "apply AXP.OS adjustments"
  raw: |
    {{ DOS_INIT }}
    {% if sub_model is defined %}
    lunch lineage_{{ sub_model }}-user && echo lunch success
    {% else %}
    lunch lineage_{{ target_model }}-user && echo lunch success
    {% endif %}
    vendor/axp/axp.sh
  args:
    executable: /bin/bash

- name: "apply AXP.OS patches (common)"
  raw: |
      {{ DOS_INIT }}
      {{ SRCPATH }}/vendor/extendrom/tools/apply_patches.sh {{ SRCPATH }}/vendor/axp/patches/common/{{ android_shortversion }}
  args:
    executable: /bin/bash
