---

- name: "disable GPG verify if dirty build"
  ansible.builtin.lineinfile:
    path: "{{ DOSPATH }}/Scripts/LineageOS-{{ los_version }}/Functions.sh"
    line: '#verifyAllPlatformTag'
    regexp: '\s+verifyAllPlatformTags\;'
  when:
    - clean_out != "true" or (override_clean_out != "true") or (skip_gpg_verify | bool)

- name: "wireguard handling by vendor/axp"
  file:
    path: "{{ SRCPATH }}/.wg.patched"
    state: touch
  when: skip_wireguard is defined and skip_wireguard | bool

- name: "apply DOS patches"
  raw: |
    {{ DOS_INIT }}
    patchWorkspace >> {{ BUILD_LOG }} 2>&1 \
      && awk -i inplace '!/enforce-product-packages-exist-internal/' vendor/lineage/config/common.mk
  register: patchout
  args:
    executable: /bin/bash

# AXP.OS adjustments (e.g wireguard, OTA,..)
- name: "apply AXP.OS adjustments"
  raw: |
    {{ DOS_INIT }}
    lunch lineage_{{ target_model }}-user && echo lunch success \
      && vendor/axp/axp.sh
  args:
    executable: /bin/bash

- name: "apply AXP.OS patches (common)"
  raw: |
      {{ DOS_INIT }}
      {{ SRCPATH }}/vendor/extendrom/tools/apply_patches.sh vendor/axp/patches/common/{{ android_shortversion }}
  args:
    executable: /bin/bash
