---

- name: "Ensure the defined sources path exists"
  file:
    path: "{{ SRCPATH }}"
    state: directory

- name: Copy DOS renamer
  copy:
    src: rename
    dest: "{{ SRCPATH }}/"
    mode: 0755
