---

- name: "Ensure the defined sources path exists"
  file:
    path: "{{ SRCPATH }}"
    state: directory

- name: Copy DOS renamer
  copy:
    src: rename
    dest: "{{ SRCPATH }}/"
    mode: 0755

- block:

    - name: "grab DOS CVE Checker"
      ansible.builtin.get_url:
        url: "{{ divest_cve_checker_download }}"
        dest: "{{ divest_cve_checker_jar }}"
        mode: 0640
    
    - name: Upload DOS CVE fixup
      copy:
        src: "cve_fixup/{{ target_model }}.patch"
        dest: cve_fixup.patch
        mode: 0640

    - name: Upload DOS getDefconfig fixup
      copy:
        src: extend_dos/getDefconfig.patch
        dest: getDefconfig.patch
        mode: 0640

    - name: Upload DOS Rebrand fixup
      copy:
        src: "extend_dos/{{ android_shortversion }}/Rebrand.patch"
        dest: rebrand_fixup.patch
        mode: 0640
      when: android_shortversion == "a10"

  when: divest_unsupported_device
