---

- name: "sync DOS"
  git: 
    repo: "{{ axp_git_repo }}"
    dest: "{{ DOSPATH }}"
    force: false
    version: "{{ axp_main_branch | d('HEAD') }}"
    clone: yes
    track_submodules: true

# sync LOS etc
- include_tasks: ../../../common/tasks/sync.yml
