---

- name: sync DOS
  shell: |
    git reset --hard
    git pull \
      && git checkout {{ axp_main_branch | d(default_axp_main_branch) }} \
      && git pull \
      && git submodule update --init --recursive
  args:
    chdir: "{{ DOSPATH }}"
    executable: /bin/bash

# sync LOS etc
- include_tasks: ../../../common/tasks/sync.yml
