---

- name: "sync DOS"
  git: 
    repo: "{{ axp_git_repo }}"
    dest: "{{ DOSPATH }}"
    force: false
    version: "{{ axp_main_branch | d('HEAD') }}"
    clone: yes
    track_submodules: true

- name: "sync LOS base & local manifests"
  include_role:
    name: common
    tasks_from: sync.yml
    vars_from: ../../../axp/common/defaults/main.yml

# (needs to be done in DOS more early then for others)
- name: "ensure the keys dir is set correctly"
  include_role:
    name: common
    tasks_from: set_keys.yml
    vars_from: ../../../axp/common/defaults/main.yml
