---

#- name: "sync DOS"
#  git: 
#    repo: "{{ axp_git_repo }}"
#    dest: "{{ DOSPATH }}"
#    force: true
#    version: "{{ axp_main_branch | d('HEAD') }}"
#    clone: yes
#    recursive: true
#    track_submodules: true

- name: "Sync DOS (lfs)"
  shell: |
      sed -i 's|git@gitlab.com:|https://gitlab.com/|' .git/config .gitmodules .git/modules/Patches/Linux/config .git/modules/PrebuiltApps/config
      git submodule update --init --recursive
      git pull
      git lfs pull
      git checkout {{ axp_main_branch | d('HEAD') }}
  args:
    executable: /bin/bash
    chdir: "{{ DOSPATH }}"
  no_log: "{{ debug_off | d(true) }}"

- name: "AXP.OS: sync LOS base & local manifests"
  include_tasks: ../../../common/tasks/sync.yml

- name: "activate special recovery manifest if needed"
  shell: |
    mv -v {{ SRCPATH }}/.repo/local_manifests/recovery.xml.disabled {{ SRCPATH }}/.repo/local_manifests/recovery.xml
    {{ repo_bin }} sync --jobs-checkout={{ max_processes }} --jobs-network={{ max_processes_sync }} {{ repo_sync_args }} {{ target_kernel_dir }}
  args:
    chdir: "{{ SRCPATH }}"
  when:
    - axp_build_recovery_only is defined and axp_build_recovery_only
    - target_model == "j5y17lte"
    
# (needs to be done in DOS more early then for others)
- name: "AXP.OS: ensure the keys dir is set correctly"
  include_tasks: ../../../common/tasks/set_keys.yml
