---

- name: "Set global vars"
  template:
    src: divested.vars.j2
    dest: "{{ BUILDHOME }}/.divested.vars"

- name: "check if a device overwrite exists"
  connection: local
  stat:
    path: "{{ role_path }}/templates/divested.vars.{{ target_model }}.j2"
  register: devvar

- name: "check if a device overwrite exists (sub_model)"
  connection: local
  stat:
    path: "{{ role_path }}/templates/divested.vars.{{ sub_model }}.j2"
  register: devvarsub
  when: sub_model is defined

- name: "Set device vars"
  template:
    src: "divested.vars.{{ target_model }}.j2"
    dest: "{{ BUILDHOME }}/.divested.vars.{{ target_model }}"
  when: devvar.stat.exists

- name: "Set device vars (sub_model)"
  template:
    src: "divested.vars.{{ sub_model }}.j2"
    dest: "{{ BUILDHOME }}/.divested.vars.{{ sub_model }}"
  when: 
   - sub_model is defined
   - devvarsub.stat.exists

- name: "Set remote path (recovery only)"
  set_fact:
    rempath: "/home/nightlies/roms/{{ ROM_FLAVOR }}/{{ target_model }}/recovery"
  when: axp_build_recovery_only is defined and axp_build_recovery_only
