---

- include: ../../common/tasks/setvars.yml
#- include: fetch_recovery.yml

- include: copy.yml

#- include: patch.yml
#  when:
#    - (override_reset_git == "undef" and reset_git == "true") or (override_reset_git == "true") or (override_sync == "true")
