---

# human readable model name
target_model_full: "OnePlus 6T"

# TWRP repo branch
git_repo_main_branch: "twrp-12.1"
los_revision: "lineage-19.1"

# device tree
DTURI: "https://github.com/AXP-OS/android_device_oneplus_fajita.git"
DTBRANCH: "twrp-a12"
DTPATH: "{{ SRCPATH }}/device/oneplus/{{ target_model }}"

# extra make targets build with TWRP (e.g. "adbd")
#RECOVERY_MKA_EXTRA_TARGETS: ""
# "recovery" when dedicated partition, otherwise "boot"
RECOVERY_MKA_TARGET: boot

# kernel 
# UNUSED atm - as kernel building in twrp-12 fails 
KERNPATH: "{{ SRCPATH }}/kernel/oneplus/sdm845"
#KERNGIT: "https://github.com/AXP-OS/android_kernel_oneplus_sdm845.git"
KERNGIT: "https://github.com/LineageOS/android_kernel_oneplus_sdm845.git"
#KERNBRANCH: "axp-a13"
KERNBRANCH: "lineage-20"
