---

# human readable model name
target_model_full: "OnePlus 7T pro"

# TWRP repo branch
git_repo_main_branch: "twrp-10.0"

# specify lunch target
LUNCHTARGET: "omni_hotdog-eng"

# device tree
DTURI: "git@github.com:sfX-android/android_device_oneplus_hotdog.git"
DTBRANCH: "android-10_shrp_lockedbl"
DTPATH: "{{ SRCPATH }}/device/oneplus/hotdog"

# kernel (prebuilt OP kernel - permissive)
KERNPATH: "kernel/oneplus/hotdog"
#KERNGIT: "https://github.com/OnePlusOSS/android_kernel_oneplus_sm8150.git"
#KERNBRANCH: "SM8150_Q_10.0"

# shrp_release_type can be set by Semaphore or here when NOT shrp_release_type = PREVIEW
shrp_release_type: Official
RELEASE_TYPE: "{{ shrp_release_type }}"

# overwrite notify var
kernel_cl: |-
  \- Kernel: prebuilt OP kernel \(stock \+ permissive\)
