---

tg_success: |
        hostvars['buildserver']['ICON_GOOD'] New build _*{{ hostvars['buildserver']['BUILDIDENT'] }}*_ has finished SUCCESSFULLY!
        \- Device: ***{{ BDEVICE }}***
        \- ROM: {{ ROM_FLAVOR }} {{ android_shortversion | replace("-","\-") | replace(".","\.") }}
        {{ rom_cl }}
        {{ kernel_cl }}
        {{ dtree_cl }}
        {{ cdtree_cl }}
        {{ dl_links }}
        SHA256:
        {{ hash.stat.checksum }}
        {{ ota_hint }}
        
        This build has been created by [Ansible](https://github.com/sfX-android/automation_scripts) + [Semaphore](https://ansible-semaphore.com) with <3 

tg_failed: |
        {{ ICON_BAD }} ***ERROR:*** Last build failed\!
        \- ROM: {{ ROM_FLAVOR }} {{ android_shortversion | replace("-","\-") | replace(".","\.") }}
        \- Device: ***{{ BDEVICE }}***
        \- Build id: _{{ BUILDIDENT | replace("-","\-") }}_
