---
# misc common vars used for all tasks

# fallback / legacy var
REPOBRANCH: undefined

# semaphore working/tmp dir
semaphore_work_dir: /opt/scs-work
semaphore_lock_dir: "{{ semaphore_work_dir }}/run"

# ensure we have a normalized & clean version tag (e.g. removing slashes from a git tag etc)
parsed_target_version: "{{ git_repo_main_branch | regex_replace('.*/','') | regex_replace('^v','') }}"
normalized_target_version: "{{ parsed_target_version | regex_replace('(\\d+)\\.(\\d+)(.*)','\\1.\\2') }}"

# build identifier used in e.g. the filename later
BUILDIDENT: "{{ ansible_date_time.date | regex_replace('-','') }}"
sm_build_id: >-
    {% if semaphore_vars.task_details.target_version is undefined %}
    {{ semaphore_vars.task_details.incoming_version | d('0000') }}
    {% else %}
    {{ semaphore_vars.task_details.target_version }}
    {% endif %}
build_id: "{{ sm_build_id | regex_replace(' ','') }}"

# full path to the repo binary
repo_bin: /home/androidsource/bin/repo

# number of threads used e.g. with repo binary etc
max_processes: 16

# ssh port where the release server is reachable (coming from the build server)
RELEASESVR_port: 22

# backwards compatible var specifying the build device (e.g. hotdog etc)
# should not be changed
BDEVICE: "{{ target_model }}"

# ccache defaults
USE_CCACHE: 1
CCACHE_EXEC: /usr/bin/ccache
CCACHE_COMPRESS: 1
CCACHE_DIR: /ssd/ccache/jenkins/{{ target_model }}-undef

# base url where the user can download released ROMs etc
leech_server: "https://leech.binbash.rocks:8008"

# notification icons
ICON_GOOD: 🎉
ICON_BAD: ☠️

# default to false
custom_release_script: false

# build vars
rempath: "/home/nightlies/roms/{{ ROM_FLAVOR }}/{{ android_shortversion }}/{{ target_model }}/"
JKZIPDIR: "/ssd/tmp/{{ ROM_FLAVOR }}/zips/{{ target_model }}"
SRCPATH: "/home/androidsource/do-not-touch/{{ ROM_FLAVOR }}"
post_cleanup_product_dir: "{{ SRCPATH }}/out/target/product/{{ target_model }}"
SEPARATE_OUT_DIR: "/ssd/{{ target_model }}/{{ ROM_FLAVOR }}-{{ android_shortversion }}/out"
manifest_paths_file: "/tmp/manifest_paths.{{ ROM_FLAVOR }}"

# build signing
sign_build: true
keysdir: '/home/androidsource/do-not-touch/KEYS/{{ ROM_FLAVOR }}-{{ android_shortversion }}_{{ target_model }}'
SRC_KEYSDIR: user-keys
KEYS_CN: "{{ ROM_FLAVOR }}"
KEYS_USER: "sfX-bot"
KEYS_SIZE: 4096
KEYS_HASHTYPE: sha256

# gen a ROM checksum
skip_gen_checksum: false

# set override defaults
override_clean_basic: 'undef'
override_clean_out: 'undef'
override_reset_git: 'undef'
override_release_build: 'undef'
override_sync: 'undef'

# cross build: problematic repos paths
prob_repo_paths:
  - "barbet-sepolicy"
  - bootable_recovery
#  - "libbrillo"

# cross build: problematic source paths
incompat_cross_version_paths:
    - bootable/recovery
    - device

# DEPRECATED by new git reset approach
incompat_cross_version_paths_DISABLED:
    - android
    - build
    - cts
    - device/
    - external/adt-infra
    - external/dnsmasq
    - external/freetype
    - external/libaom
    - external/libbrillo
    - external/libhevc
    - external/libtextclassifier
    - external/perfetto
    - external/chromium-libpac
    - external/chromium-webview
    - external/guice
    - external/mesa3d
    - external/okhttp
    - external/ppp
    - external/robolectric-shadows
    - external/selinux
    - external/sonivox
    - external/v8
    - frameworks/av
    - frameworks/hardware/interfaces
    - frameworks/ml
    - frameworks/native
    - frameworks/opt/net/voip
    - frameworks/opt/net/wifi
    - frameworks/opt/telephony
    - frameworks/support
    - hardware/libhardware_legacy
    - hardware/marvell
    - hardware/qcom/sm7150
    - hardware/qcom/sm7250
    - hardware/qcom/sm8150
    - hardware/qcom/sm8150p
    - hardware/qcom-caf
    - hardware/qcom/wlan
    - hardware/qcom/Android.mk    
    - kernel/
    - packages/apps/Bluetooth
    - packages/apps/PermissionController
    - packages/apps/PhoneCommon
    - packages/apps/Trebuchet
    - packages/apps/Updater
    - packages/modules/NetworkStack
    - packages/providers/MediaProvider
    - platform_testing
    - prebuilts/gcc/darwin-x86/x86/x86_64-linux-android-4.9
    - prebuilts/gcc/linux-x86/x86/x86_64-linux-android-4.9
    - prebuilts/r8
    - .repo/repo
    - system/connectivity/wificond
    - system/core
    - system/keymaster
    - system/security
    - system/sepolicy
    - test/
    - tools/
    - vendor/lineage
    - vendor/fdroid
    - vendor/cm
    - vendor/nxp

# manual security patch handling for PIE
#topic:P_asb_2022-02 OR # merged officially!
#topic:P_asb_2022-03 OR # merged officially!
#topic:P_asb_2022-04 OR # merged officially!
# https://review.lineageos.org/q/topic:xxxx
SECPATCH_DATE_PIE: "2023-06"
sec_patch_topics_pie: >-
      topic:P_asb_2022-05 OR
      topic:P_asb_2022-06 OR
      topic:P_asb_2022-07 OR
      topic:P_asb_2022-08 OR
      topic:P_asb_2022-09 OR
      topic:P_asb_2022-10 OR
      topic:P_asb_2022-11 OR
      topic:P_asb_2022-12 OR
      topic:P_asb_2023-01 OR
      topic:P_asb_2023-02 OR
      topic:P_asb_2023-03 OR
      topic:P_asb_2023-04 OR
      topic:P_asb_2023-05 OR
      topic:P_asb_{{ SECPATCH_DATE_PIE }}
