---
# human readable model name
target_model_full: "LG G4"

# boot debugger path & config
extendrom_debug_path_default: /persist
extendrom_debug_path_size_full_default: 500 
extendrom_debug_path_size_kernel_default: 100
extendrom_debug_path_size_selinux_default: 200
extendrom_debug_path_size_crash_default: 200

# path to the kernel dir (req for e.g. wireguard)
target_kernel_dir: kernel/lge/msm8992

# set output dir to sub model (specific g4 use case - this overwrites roles/common)
JKZIPDIR: "/ssd/tmp/{{ ROM_FLAVOR }}/zips/{{ sub_model }}"

# defaults override:
rempath: "/home/nightlies/roms/{{ ROM_FLAVOR }}/{{ sub_model }}/"
post_cleanup_product_override: "{{ SEPARATE_OUT_DIR }}/target/product/{{ sub_model }}"

# defaults overridei (notify):
device_cl: |-
  ***{{ target_model_full }}*** ***\({{ sub_model | replace("-","\-") | replace("_","\_") }}\)*** \- ***{{ ROM_FLAVOR }} {{ android_shortversion }}***

dl_links: |-
  ***Download:*** [{{ ROMFILE.stdout | replace("-","\-") | replace("_","\_") | replace(".","\.") }} ]({{ leech_server }}/e-os/{{ android_shortversion }}/{{ sub_model }})

dtree_cl: |-
  \- device tree: [commits](https://github.com/LGgFour/android_device_lge_g4/commits/{{ ROM_FLAVOR }}-{{ android_shortversion }})

cdtree_cl: |-
  \- common tree: [commits](https://github.com/LGgFour/android_device_lge_g4-common/commits/{{ ROM_FLAVOR }}-{{ android_shortversion }})

kernel_cl: |-
  \- Kernel: [commits](https://github.com/LGgFour/kernel_lge_msm8992/commits/{{ ROM_FLAVOR }}-{{ android_shortversion }})
