---

- name: "Apply Bluetooth patch (audio fix)"
  shell: "patch -p1 < ../../../../../external/patches/vendor_qcom_opensource_packages_apps_Bluetooth.patch && touch {{ SRCPATH }}/.tmp/bt.patched"
  args:
    chdir: "{{ SRCPATH }}/vendor/qcom_opensource/packages/apps/Bluetooth"
    creates: "{{ SRCPATH }}/.bt.patched"
  when: apply_bt_app_patch is defined and apply_bt_app_patch == "true"

- name: "PIE: applying misc patches"
  shell: "source build/envsetup.sh > /dev/null && echo 'applying misc patch:' && {{ item }}"
  args:
    executable: /bin/bash
    chdir: "{{ SRCPATH }}"
  loop:
    - "repopick -f 307334/2 -P frameworks/base/"                      # scale font patch
    - "git apply external/patches/frameworks_base_shadercache.patch"  # always use shader cache
#    - "cd kernel/lge/msm8992 && git reset --hard 5111999f7182a828dd0adad72a38a17a57933d72"
#    - "wget https://github.com/aoleary/G4-Titan-Kernel/commit/289e2b72a917da57f76c0e5edc7af84662044a4d.patch -O /tmp/patch1"
#    - "wget https://github.com/aoleary/G4-Titan-Kernel/commit/8390b58884b901fe72573911a6992515a2b31315.patch -O /tmp/patch2"
#    - "cd kernel/lge/msm8992 && git apply /tmp/patch1"
#    - "cd kernel/lge/msm8992 && git apply /tmp/patch2"

- set_fact:
    SECPATCH_DATE: "2023-01"

- name: "PIE: applying security patches up to: {{ SECPATCH_DATE }}-05"
  shell: "source build/envsetup.sh > /dev/null && echo 'applying {{ item }}:' && repopick -f -t {{ item }}"
  args:
    executable: /bin/bash
    chdir: "{{ SRCPATH }}"
  loop:
    #- "P_asb_2022-02" # merged officially!
    #- "P_asb_2022-03" # merged officially!
    #- "P_asb_2022-04" # merged officially!
    - "P_asb_2022-05"
    - "P_asb_2022-06"
    - "P_asb_2022-07"
    - "P_asb_2022-08"
    - "P_asb_2022-09"
    - "P_asb_2022-10"
    - "P_asb_2022-11"
    - "P_asb_2022-12"
    - "P_asb_{{ SECPATCH_DATE }}"
    
- name: "PIE: bump security patch version string to: {{ SECPATCH_DATE }}-05"
  lineinfile:
    path: "{{ SRCPATH }}/build/core/version_defaults.mk"
    regexp: "PLATFORM_SECURITY_PATCH := .*"
    line: "PLATFORM_SECURITY_PATCH := {{ SECPATCH_DATE }}-05"
