---

- name: "A12: applying required patches"
  shell: "source build/envsetup.sh > /dev/null && echo 'applying {{ item }}:' && repopick -f {{ item }}"
  args:
    executable: /bin/bash
    chdir: "{{ SRCPATH }}"
  loop:
    - "320591/2 -P system/bpf"              # system/bpf 
    - "320592/2 -P system/netd"             # system/netd
    - "326385/3 -P packages/modules/adb"    # packages/modules/adb
    - "318097/1 -P art"                     # memfd: art
    - "287706/8 -P external/perfetto"       # memfd: external/perfetto

#- name: "A12: manual adjustments"
#  shell: "{{ item }}"
#  args:
#    executable: /bin/bash
#    chdir: "{{ SRCPATH }}"
#  loop:
#    - "cd vendor/lineage && git revert 8f67d055b36d992f2f09aa6f733aa06ee3d5b917"
