---

- name: "Apply Bluetooth patch (audio fix)"
  shell: "patch -p1 < ../../../../../external/patches/vendor_qcom_opensource_packages_apps_Bluetooth.patch && touch {{ SRCPATH }}/.tmp/bt.patched"
  args:
    chdir: "{{ SRCPATH }}/vendor/qcom_opensource/packages/apps/Bluetooth"
    creates: "{{ SRCPATH }}/.bt.patched"
