---

REPO_UPLOAD_ISO_SRV: "{{ groups.downloadserver[0] }}"
RELEASE_TYPE: nightly

repo_mAid_http: "https://code.binbash.rocks:8443/mAid/build.git"
maid_home_path: "build_maid"
SRCPATH: "{{ maid_home_path }}"
maid_build_path: "/var/tmp"

# default mAid kernel if not specified in Semaphore
maid_kernel: linux515

# default build size if not specified in Semaphore
maid_size: light

# default build vars
debug_build: 'false'
skip_clean_build: 'false'

commit_uri_id: >
        {% if RELEASE_TYPE == "nightly" %}branch/nightly{% else %}tag/v{{ MAID_VERSION }}{% endif %}

tg_success: |
        {{ ICON_GOOD }} ***New build has finished\!***
        
        ***mAid {{ MAID_VERSION | d('nightly') | replace("!","\!") | replace("-","\-")  | replace(".","\.") | replace(">","\>") }} \- {{ RELEASE_TYPE | d('nightly') | replace("-","\-")  | replace(".","\.") | replace(">","\>") }}***

        \- Size: **{{ maid_size }}** \(see [wiki](https://code.binbash.rocks:8443/mAid/build/wiki/Frequently-Asked-Questions#what-means-light-full)\)
        \- Changes: [commits](https://code.binbash.rocks:8443/mAid/build/commits/{{ commit_uri_id }})
        \- Download: [ISO]({{ dl_link }})
        
        ***MD5 hash:***
        {{ md5hash.stdout | default("error getting hash") }}
        
        This build has been created by my [Ansible project](https://github.com/sfX-android/automation_scripts) \+ [Semaphore](https://ansible-semaphore.com) with ❤️

tg_failed: |
        {{ ICON_BAD }} ***ERROR:*** Last build failed\!
        
        \- mAid v{{ MAID_VERSION | d('nightly') | replace("!","\!") | replace("-","\-")  | replace(".","\.") | replace(">","\>") }}
        \- Build id: _{{ BUILDIDENT | replace("-","\-") }}_
