---

commit_uri_id: >
        {% if RELEASE_TYPE == "nightly" %}branch/nightly{% else %}tag/v{{ MAID_VERSION }}{% endif %}

tg_success: |
        {{ ICON_GOOD }} ***New build has finished\!***
        
        ***mAid v{{ MAID_VERSION | d('nightly') | replace("!","\!") | replace("-","\-")  | replace(".","\.") | replace(">","\>") }} \- {{ RELEASE_TYPE | d('nightly') | replace("-","\-")  | replace(".","\.") | replace(">","\>") }}***
        
        \- Changes: [commits](https://code.binbash.rocks:8443/mAid/build/commits/{{ commit_uri_id }})
        \- Download: [ISO]({{ dl_link }})
        
        ***MD5 hash:***
        {{ md5hash.stdout | default("error getting hash") }}
        
        This build has been created by my [Ansible project](https://github.com/sfX-android/automation_scripts) \+ [Semaphore](https://ansible-semaphore.com) with ❤️

tg_failed: |
        {{ ICON_BAD }} ***ERROR:*** Last build failed\!
        
        \- mAid v{{ MAID_VERSION | d('nightly') | replace("!","\!") | replace("-","\-")  | replace(".","\.") | replace(">","\>") }}
        \- Build id: _{{ BUILDIDENT | replace("-","\-") }}_
