---

- name: "Building: {{ BDEVICE }} - {{ ROM_FLAVOR }} (timeout: 4 hours)"
  debug:
    msg: |
      #
      
      Build {{ BDEVICE }} - {{ ROM_FLAVOR }} - {{ git_repo_main_branch }} has been started, lean back and let the CPUs burn ...
      
      Variables in use:

      BDEVICE: {{ BDEVICE }}
      target_model_full: {{ target_model_full }} - target_model: {{ target_model }}{% if sub_model is defined %} - sub_model: {{ sub_model }}{% endif%}
      
      ROM_FLAVOR: {{ ROM_FLAVOR }}
      RELEASE_TYPE: {{ RELEASE_TYPE | d("N/A") }}
      android_shortversion: {{ android_shortversion }}
      normalized_target_version: {{ normalized_target_version }}
      sign_build: {{ sign_build | d(false) }}
      USE_CCACHE: {{ USE_CCACHE | d("N/A") }}
      CCACHE_DIR: {{ CCACHE_DIR | d("N/A") }}
      use_extendrom: {{ use_extendrom | d(false) }}
      extendrom_package_list: {{ extendrom_package_list | d("N/A") }}
      rempath: {{ rempath | d("N/A") }}
      
      clean_basic: {{ clean_basic | d("N/A") }} | override_clean_basic: {{ override_clean_basic | d("N/A") }}
      clean_out: {{ clean_out | d("N/A") }} | override_clean_out: {{ override_clean_out | d("N/A") }}
      reset_git: {{ reset_git | d("N/A") }} | override_reset_git: {{ override_reset_git | d("N/A") }}
      release_build: {{ release_build | d("N/A") }} | override_release_build: {{ override_release_build | d("N/A") }}
      
      #

- name: "Building ROM: {{ BDEVICE }} - {{ ROM_FLAVOR }}"
  shell: "source ~/.bashrc && ./build_{{ target_model }}_{{ android_shortversion }}_{{ ROM_FLAVOR }}.sh > build_{{ target_model }}_{{ android_shortversion }}_{{ ROM_FLAVOR }}.log 2>&1"
  args:
    executable: /bin/bash
  async: 14400
  poll: 30
  register: buildresult
  ignore_errors: true

- name: "Grab version from vendor dir"
  shell: 'grep "PRODUCT_VERSION_MAJOR = " vendor/{{ vendor_version }}/config/common.mk | cut -d "=" -f 2 | tr -d " "'
  args:
    chdir: "{{ SRCPATH }}"
  register: version_major
  when: vendor_version is defined

- name: "Grab version from vendor dir"
  shell: 'grep "PRODUCT_VERSION_MINOR = " vendor/{{ vendor_version }}/config/common.mk | cut -d "=" -f 2 | tr -d " "'
  args:
    chdir: "{{ SRCPATH }}"
  register: version_minor
  when: vendor_version is defined
