---

- name: "Building ROM: {{ BDEVICE }} - {{ ROM_FLAVOR }} (timeout: 3 hours)"
  debug:
    msg: "Build {{ BDEVICE }} - {{ ROM_FLAVOR }} - {{ REPOBRANCH }} has been started, lean back and let the CPUs burn ..."

- name: "Building ROM: {{ BDEVICE }} - {{ ROM_FLAVOR }}"
  shell: "./build_{{ target_model }}_{{ android_shortversion }}_{{ ROM_FLAVOR }}.sh > build_{{ target_model }}_{{ android_shortversion }}_{{ ROM_FLAVOR }}.log 2>&1"
  async: 10800
  poll: 30
  register: buildresult
  ignore_errors: true

- name: "Grab version from vendor dir"
  shell: grep "PRODUCT_VERSION_MAJOR = " vendor/lineage/config/common.mk | cut -d "=" -f 2 | tr -d " "
  args:
    chdir: "{{ SRCPATH }}"
  register: version_major
  when: vendor_version is defined

- name: "Grab version from vendor dir"
  shell: grep "PRODUCT_VERSION_MINOR = " vendor/lineage/config/common.mk | cut -d "=" -f 2 | tr -d " "
  args:
    chdir: "{{ SRCPATH }}"
  register: version_minor
  when: vendor_version is defined
