---

- fail:
    msg: "Build FAILED! Check log for details: /tmp/{{ inventory_hostname }}/build_{{ target_model }}_{{ android_shortversion }}_{{ ROM_FLAVOR }}.log"
  when:
    - buildresult.rc is undefined or buildresult.rc != 0

- block:
    
    - set_fact:
        LOCFILE: "{{ PREFIXFNAME }}.*-{{ RELEASE_TYPE }}.*\\.zip"
      when:
        - ROM_FLAVOR != "TWRP"

    - set_fact:
        LOCFILE: "{{ PREFIXFNAME }}.*-{{ RELEASE_TYPE }}.*\\.img"
      when:
        - ROM_FLAVOR == "TWRP"

    - set_fact:
        LOCFILE: "recovery.img"
      when:
        - ROM_FLAVOR == "axp"
        - axp_build_recovery_only is defined and axp_build_recovery_only
    
    - set_fact:
        JKZIPDIR: "{{ axp_finalzip_dir }}"
      when:
        - ROM_FLAVOR == "axp"
    
    - name: "Get current build filename"
      shell: "find ./ -maxdepth 1 -regex '.*/{{ LOCFILE }}' | tr -d '\\n' | sed 's#^\\./##g'"
      args:
        chdir: "{{ JKZIPDIR }}"
      register: ROMFILE
    
    - name: "Copy build.prop for OTA"
      shell: "cp -vf {{ SRCPATH }}/out/target/product/*/system/build.prop {{ JKZIPDIR }}/{{ ROMFILE.stdout }}.prop"
      when:
        - ROM_FLAVOR != "TWRP"
        - ROM_FLAVOR != "SHRP"

 # when: custom_release_script is undefined or not custom_release_script
