---

- fail:
    msg: "Build FAILED! Check log for details: /tmp/{{ inventory_hostname }}/build_{{ target_model }}_{{ android_shortversion }}_{{ ROM_FLAVOR }}.log"
  when:
    - buildresult.rc is undefined or buildresult.rc != 0

- name: "POST: Clean-Up out/"
  file:
    path: "{{ post_cleanup_dir }}"
    state: absent
  when:
    - post_cleanup_dir is defined
    - (override_clean_out is undefined and clean_out == "true") or (override_clean_out is defined and override_clean_out == "true") or (post_cleanup is defined and post_cleanup == "true")
