---

- fail:
    msg: "Build FAILED! Check log for details: /tmp/{{ inventory_hostname }}/build_{{ target_model }}_{{ android_shortversion }}_{{ ROM_FLAVOR }}.log"
  when:
    - buildresult.rc is undefined or buildresult.rc != 0

- name: "get build date"
  shell: "grep ro.build.date.utc {{ SRCPATH }}/out/target/product/*/system/build.prop | cut -d '=' -f2 "
  register: build_date_utc

- block:
    
    - set_fact:
        LOCFILE: "{{ PREFIXFNAME }}.*-{{ RELEASE_TYPE }}.*\\.zip"
      when:
        - ROM_FLAVOR != "TWRP"

    - set_fact:
        LOCFILE: "{{ PREFIXFNAME }}.*-{{ RELEASE_TYPE }}.*\\.img"
      when:
        - ROM_FLAVOR == "TWRP"

    - set_fact:
        LOCFILE: "{{ axp_recovery_filename }}"
      when:
        - ROM_FLAVOR == "axp"
        - axp_build_recovery_only is defined and axp_build_recovery_only
    
    - name: "Get current build filename"
      shell: "find ./ -maxdepth 1 -regex '.*/{{ LOCFILE }}' | tr -d '\\n' | sed 's#^\\./##g'"
      args:
        chdir: "{{ JKZIPDIR }}"
      register: ROMFILE_NONAXP

    - name: "AXP: set unstable (rename zip)"
      shell: |
          mv {{ JKZIPDIR }}/{{ ROMFILE_NONAXP.stdout }} {{ JKZIPDIR }}/{{ ROMFILE_NONAXP.stdout | regex_replace('-dos-','-dos-unstable-') }}
      when: axp_unstable_build | bool | d(False)

    - name: "AXP: set unstable (reset variable)"
      shell: "echo {{ ROMFILE_NONAXP.stdout | regex_replace('-dos-','-dos-unstable-') }}"
      register: ROMFILE_AXP
      when: axp_unstable_build | bool | d(False)

    - name: "Set ROMFILE var"
      set_fact:
          ROMFILE: "{{ ROMFILE_NONAXP | d(ROMFILE_AXP) }}"
    
    - name: "Copy build.prop for OTA"
      shell: "cp -vf {{ SRCPATH }}/out/target/product/*/system/build.prop {{ JKZIPDIR }}/{{ ROMFILE.stdout }}.prop"
      when:
        - ROM_FLAVOR != "TWRP"
        - ROM_FLAVOR != "SHRP"
        - axp_build_recovery_only is undefined or (axp_build_recovery_only is defined and not axp_build_recovery_only)

  when: custom_release_script is undefined or (custom_release_script is defined and not custom_release_script)
