---

- set_fact:
    LOCFILE: "{{ PREFIXFNAME }}-.*-{{ RELEASE_TYPE }}.*\\.zip"

- name: "Get current ROM filename"
  shell: "find ./ -maxdepth 1 -regex '.*/{{ LOCFILE }}' | tr -d '\n'"
  args:
    chdir: "{{ JKZIPDIR }}"
  register: ROMFILE

- name: "Generate hash for {{ ROMFILE.stdout }}"
  stat:
    path: "{{ JKZIPDIR }}/{{ ROMFILE.stdout }}"
    checksum_algorithm: sha256
  register: hash

- name: "Write hash {{ ROMFILE.stdout }}.sha256sum"
  shell: "echo {{ hash.stat.checksum }} > {{ ROMFILE.stdout }}.sha256sum"
  args:
    chdir: "{{ JKZIPDIR }}"
