---

# build process 
- include_tasks: build.yml
- include_tasks: grab_log.yml
# failure checking of build
- include_tasks: end_build.yml
# generate sha hash
- include_tasks: gen_checksum.yml
  when: not skip_gen_checksum
# post clean up if requested
- include_tasks: post_cleanup.yml
  when: post_cleanup | bool | d(False)

