---

# human readable model name
target_model_full: "OnePlus 7T pro"

# SHRP repo branch
git_repo_main_branch: "v3_10.0"

DTURI: "git@github.com:sfX-android/android_device_oneplus_hotdog.git"
DTBRANCH: "android-10_shrp_lockedbl"
KERNPATH: "kernel/oneplus/hotdog"
DTPATH: "{{ SRCPATH }}/device/oneplus/hotdog"

LUNCHTARGET: "omni_hotdog-eng"
# shrp_release_type can be set by Semaphore or here when NOT shrp_release_type = PREVIEW
shrp_release_type: Official
RELEASE_TYPE: "{{ shrp_release_type }}"
TWRPXML: default.xml

# notification vars
device_cl: |-
  ***{{ target_model_full }}*** ***\({{ target_model | replace("-","\-") | replace("_","\_") }}\)*** \- ***{{ ROM_FLAVOR | replace("-","\-") }} {{ git_repo_main_branch | replace("-","\-") | replace("_","\_") | replace(".","\.") }}***

kernel_cl: |-
  \- Kernel: [commits](https://github.com/sfX-android/android_kernel_oneplus_sm8150/commits/android-10.0_permissive)

dtree_cl: |-
  \- Device tree: [commits](https://github.com/sfX-android/android_device_oneplus_hotdog/commits/android-10_shrp)

