---
 
- name: "Apply signing fixes"
  shell: "patch -p1 < device/oneplus/sm8150-common/patches/{{ item }}"
  args:
    chdir: "{{ SRCPATH }}"
  loop:
    - build_make_tools_releasetools_fixpython.patch

- name: "apply AXP.OS kernel patches (hotdog)"
  shell: |
      source ~/.bashrc
      source build/envsetup.sh \
        && source ../../Scripts/init.sh \
        && vendor/extendrom/tools/apply_patches.sh vendor/axp/patches/kernel \
        && cp -v kernel/wireguard-linux-compat/src/compat/compat.h {{ target_kernel_dir }}/net/wireguard/compat/
  args:
    chdir: "{{ SRCPATH }}"
    executable: "/bin/bash"
