---
 
- name: "Apply signing fixes"
  shell: "patch -p1 < device/oneplus/sm8150-common/patches/{{ item }}"
  args:
    chdir: "{{ SRCPATH }}"
  loop:
    - build_make_tools_releasetools_fixpython.patch

- name: "apply AXP.OS kernel patches (hotdog)"
  raw: |
      {{ DOS_INIT }}
      vendor/extendrom/tools/apply_patches.sh {{ SRCPATH }}/vendor/axp/patches/kernel \
        && cp -v kernel/wireguard-linux-compat/src/compat/compat.h {{ target_kernel_dir }}/net/wireguard/compat/
  args:
    executable: /bin/bash
