---
 
#- name: "Apply signing fixes"
#  shell: "patch -p1 < device/oneplus/sm8150-common/patches/{{ item }}"
#  args:
#    chdir: "{{ SRCPATH }}"
#  loop:
#    - build_make_tools_releasetools_fixpython.patch

- name: "apply AXP.OS kernel wireguard patch"
  raw: |
      {{ DOS_INIT }}
      vendor/extendrom/tools/apply_patches.sh {{ SRCPATH }}/vendor/axp/patches/kernel \
        && cp -v kernel/wireguard-linux-compat/src/compat/compat.h {{ target_kernel_dir }}/net/wireguard/compat/
  args:
    executable: /bin/bash

- name: "temporary hotfix for page_alloc.c"
  shell: |
    git stash save page_alloc.c
    git fetch https://github.com/LineageOS/android_kernel_oneplus_sm8150 refs/changes/34/376534/1 && git cherry-pick FETCH_HEAD
    git stash pop
  args:
    chdir: "{{ SRCPATH }}/{{ target_kernel_dir }}"
