---

# human readable model name
target_model_full: "Google Pixel 6a"

# extendrom stuff
use_extendrom: "true"
#extendrom_package_list: "noGOSpdfviewer noGOSvanadium noGOSauditor noGOScontacts noSeedvault noWizard"

# do not gen a ROM checksum
skip_gen_checksum: true

# GOS_KERNEL_BRANCH:
# ROM_NAME:
# ROM_BL_TYPE:
# lunch_buildtype:

