---

os_name: "X.OS" 

# git
git_repo_main_manifests: "https://github.com/LineageOS/android.git"

# DOS repo + main branch
xos_git_repo: "git@github.com:sfX-android/build_divestos.git"
default_xos_main_branch: '2023-07-14'
git_repo_local_manifests_branch: "{{ ROM_FLAVOR }}-{{ android_shortversion }}"

# build vars
los_version: "{{ android_shortversion | replace('a13','20.0') | replace('a12','19.1') | replace('a9','16.0') }}"
git_repo_main_branch: "lineage-{{ los_version }}"
DOSPATH: "/home/androidsource/do-not-touch/{{ ROM_FLAVOR }}"
SRCPATH: "{{ DOSPATH }}/Build/LineageOS-{{ los_version }}"
ZIPDIR: "/ssd/tmp/{{ ROM_FLAVOR }}/{{ BDEVICE }}"
USE_CCACHE: 1
rempath: "/home/nightlies/roms/{{ ROM_FLAVOR }}/{{ android_shortversion }}/{{ target_model }}/"
RELEASE_TYPE: dos
ROM_VERSION: "{{ build_id }}"
PREFIXFNAME: "{{ os_name }}-{{ los_version }}"

# extendrom stuff
use_extendrom: "true"
extendrom_package_list: "additional_repos.xml Phonesky Lawnchair-latest SignMagisk AuroraServices AuroraStore MicrogGmsCore GsfProxy"

# keys
KEYS_CN: "{{ os_name }}"
KEYS_SIZE: 8192
KEYS_HASHTYPE: sha512
keysdir: "{{ DOSPATH }}/Signing_Keys/4096pro/{{ target_model }}/"

# notification vars
ota_hint: |-
  ***OTA Update:*** supported

rom_cl: |-
  ***Changes:***
  \- divestOS: [Changelog](https://divestos.org/pages/news)
  \- X\.OS: [Changelog](https://x.os.binbash.rocks/dl.html)

dl_links: |-
  ***Download:*** [{{ ROMFILE.stdout | regex_escape() }} ]({{ leech_server }}/{{ ROM_FLAVOR }}/{{ android_shortversion }}/{{ target_model }})
