---

# human readable model name
target_model_full: "Samsung J5 \\- 2017"

# manifests
git_repo_local_manifests: "https://code.binbash.rocks:8443/MVA-VoLTE/local_manifests.git"
git_repo_local_manifests_branch: "eos-q"

# extendrom stuff
use_extendrom: "true"
extendrom_package_list: "Lawnchair-latest F-Droid F-DroidPrivilegedExtension additional_repos.xml AuroraStore AuroraServices Phonesky noEOSCamera opencamera_j5_latest"
extendrom_fdroid_repos: "microg.xml divest.xml izzysoft.xml nanolx.xml molly.xml nailyk.xml threema.xml futo_org.xml"

# notification vars (overwriting the defaults
kernel_cl: |-
  \- Kernel: [commits](https://code.binbash.rocks:8443/MVA-VoLTE/android_kernel_samsung_exynos7870/commits/branch/android-10.0)

dtree_cl: |-
  \- Device tree: [commits](https://code.binbash.rocks:8443/MVA-VoLTE/android_device_samsung_j5y17lte/commits/branch/eos-q)

cdtree_cl: |-
  \- Common tree: [commits](https://code.binbash.rocks:8443/MVA-VoLTE/android_device_samsung_exynos7870-common/commits/branch/eos-q)

# DEVICE specific security patch handling
# depends on the used custom OS and device model so has to be in the device vars
sec_patch_pick_branch: "lineage-17.1" 
sec_patch_date_last: "{{ current_year }}-11"
# checking for topics: https://review.lineageos.org/q/topic:Q_asb_2023-11
sec_patch_topics: >-
      topic:Q_asb_2023-03 OR
      topic:Q_asb_2023-04 OR
      topic:Q_asb_2023-05 OR
      topic:Q_asb_2023-06 OR
      topic:Q_asb_2023-07 OR
      topic:Q_asb_2023-08 OR
      topic:Q_asb_2023-09 OR
      topic:Q_asb_2023-10 OR
      topic:Q_asb_{{ sec_patch_date_last }}
