---

# human readable model name
target_model_full: "Samsung J5 \\- 2017"

# manifests
git_repo_local_manifests: "https://code.binbash.rocks:8443/MVA-VoLTE/local_manifests.git"
git_repo_local_manifests_branch: "eos-q"

# extendrom stuff
use_extendrom: "true"
extendrom_package_list: "Lawnchair-latest F-Droid F-DroidPrivilegedExtension additional_repos.xml AuroraStore AuroraServices Phonesky noEOSCamera opencamera_j5_latest"

# notification vars (overwriting the defaults
kernel_cl: |-
  \- Kernel: [commits](https://code.binbash.rocks:8443/MVA-VoLTE/android_kernel_samsung_exynos7870/commits/branch/android-10.0)

dtree_cl: |-
  \- Device tree: [commits](https://code.binbash.rocks:8443/MVA-VoLTE/android_device_samsung_j5y17lte/commits/branch/eos-q)

cdtree_cl: |-
  \- Common tree: [commits](https://code.binbash.rocks:8443/MVA-VoLTE/android_device_samsung_exynos7870-common/commits/branch/eos-q)
