---

- name: Ensure a previous build script is gone
  file:
    path: "{{ BUILDHOME }}/build_{{ target_model }}_{{ android_shortversion }}_{{ ROM_FLAVOR }}.sh"
    state: absent

- name: Upload build script
  template:
    src: build.sh.j2
    dest: "{{ BUILDHOME }}/build_{{ target_model }}_{{ android_shortversion }}_{{ ROM_FLAVOR }}.sh"
    mode: 0700
