---

- name: "mAid build info"
  debug:
    msg: |
      __________________________________________________
      
      Build variables:
      
      Version: {{ MAID_VERSION | d('nightly') }}
      Type: {{ RELEASE_TYPE | d('nightly') }}
      Build server: {{ groups.buildserver[0] }}
      Leech server: {{ groups.downloadserver[0] }}
      private notify: {{ debug_build }}
      release build & packages: {{ release_build_def }}
      
      __________________________________________________

- name: "Starting mAid build - let the CPUs burn ......"
  shell: >
    buildiso -p mAid \
      {% if skip_clean_build | bool %}-c{% endif %} \
      -r {{ maid_build_path }}/mAid_work \
      -t {{ maid_build_path }}/mAid_work/iso \
      -d xz \
      > >(tee /tmp/build_MAID_stdout.log) \
      2> >(tee /tmp/build_MAID_error.log >&2)
  environment:
    MAID_VERSION: "{{ MAID_VERSION | d('') }}"
    MAID_TYPE: "{{ RELEASE_TYPE | d('nightly') }}"
    REPO_UPLOAD_PKG_SRV: >-
        {% if release_build_def != 'true' %}{{ REPO_UPLOAD_PKG_SRV }}{% endif %}
    REPO_UPLOAD_PKG_USER: "{{ vault_buildmaidserver_user }}"
    REPO_UPLOAD_PKG_PATH: "/home/nightlies/roms/mAid/.repo/"
    REPO_UPLOAD_ISO_SRV: >-
        {% if release_build_def != 'true' %}{{ REPO_UPLOAD_ISO_SRV }}{% endif %}
    REPO_UPLOAD_ISO_USER: "{{ vault_buildmaidserver_user }}"
    REPO_UPLOAD_ISO_PATH: "/home/nightlies/roms/mAid/"
  args:
    executable: /bin/bash
    chdir: build_maid
  register: buildresult
  delegate_to: "{{ groups.buildserver[0] }}"

- name: Fetch build logs
  fetch:
    src: "{{ item }}"
    dest: /tmp/
  loop:
    - "/tmp/build_{{ ROM_FLAVOR }}_error.log"
    - "/tmp/build_{{ ROM_FLAVOR }}_stdout.log"
