---

- include_tasks: set_vars.yml
  become: no
  
- include_tasks: sync.yml
  become: no
  
- include_tasks: build.yml
  become: no

- include_tasks: get_hash.yml
  become: no
  when: buildresult.rc == 0
