---

- set_fact:
    MAID_VERSION: ""
  when: RELEASE_TYPE is undefined or RELEASE_TYPE == "nightly"

- set_fact:
    MAID_VERSION: "{{ RELEASE_VERSION }}"
  when: 
    - RELEASE_TYPE is defined and RELEASE_TYPE != "nightly"

- set_fact:
    release_build_def: >-
        {% if override_release_build is defined and override_release_build != "undef" %}{{ override_release_build | bool }}{% else %}{{ release_build | bool }}{% endif %}

- set_fact:
    dl_link: >-
        {% if RELEASE_TYPE == "nightly" %}{{ leech_server }}/mAid/{% else %}{{ leech_server }}/mAid/stable{% endif %}
