---

- set_fact:
    MAID_VERSION: ""
  when: RELEASE_TYPE == "nightly"

- set_fact:
    MAID_VERSION: "{{ RELEASE_VERSION }}"
  when: RELEASE_TYPE != "nightly"

- set_fact:
    release_build_def: >-
        {% if override_release_build is defined and override_release_build != "" %}{{ override_release_build | bool }}{% else %}{{ release_build | bool }}{% endif %}
