---

- name: "Ensure we do not delete local changes w/o a backup"
  become: no
  shell: git add -A . && git stash save befreset-$(date +%F_%T)
  args:
    executable: /bin/bash
    chdir: "{{ maid_home_path }}"

- name: "Synching mAid build repo"
  become: no
  git:
    repo: "{{ repo_mAid_http }}"
    dest: "{{ maid_home_path }}"
    version: "{% if RELEASE_VERSION is defined and git_repo_branch is defined %}{{ git_repo_branch }}{% else %}nightly{% endif %}"
    force: yes
  delegate_to: "{{ groups.buildserver[0] }}"
