---

- name: "Fetch add_img_to_target_files.patch"
  get_url:
    url: https://raw.githubusercontent.com/Wunderment/build_tasks/master/source/add_img_to_target_files.py-17.1.patch
    dest: "{{ SRCPATH }}/add_img_to_target_files.patch"

- name: "Fetch sign_target_files_apks.patch"
  get_url:
    url: https://raw.githubusercontent.com/Wunderment/build_tasks/master/source/sign_target_files_apks.py-17.1.patch
    dest: "{{ SRCPATH }}/sign_target_files_apks.patch"

- name: "Apply build_make_core_Makefile_fixsigning.patch"
  shell: "git apply device/oneplus/hotdog/patches/build_make_core_Makefile_fixsigning.patch"
  args:
    chdir: "{{ SRCPATH }}"

- name: "Apply img and sign apk patches"
  shell: "patch -p0 < '{{ item }}'"
  args:
    chdir: "{{ SRCPATH }}/build/make/tools/releasetools"
  loop:
    - "../../../../sign_target_files_apks.patch"
    - "../../../../add_img_to_target_files.patch"
    
- name: "Apply {{ item }} on top of the Wunderment patches"
  shell: "git apply device/oneplus/hotdog/patches/build_make_core_Makefile_fixsigning.patch"
  args:
    chdir: "{{ SRCPATH }}"
  loop:
    - device/oneplus/hotdog/patches/build_make_tools_releasetools_sign_target_files_apks.patch
    - device/oneplus/hotdog/patches/build_make_tools_releasetools_add_img_to_target_files.patch

- name: "Cleanup tmp patch files"
  file:
    path: "{{ SRCPATH }}/{{ item }}"
    state: absent
  loop:
    - add_img_to_target_files.patch
    - sign_target_files_apks.patch
