---
# dynamic variables based on given pipeline vars

- set_fact:
    dtree_cl: "\\- Device tree: [commits](https://github.com/sfX-android/android_device_oneplus_hotdog/commits/eos-q_lockedbl)\n"
  connection: local
  when: EOS_RELEASE_TYPE == "CUSTOM"

- set_fact:
    dtree_cl: "\\- Device tree: [commits](https://github.com/sfX-android/android_device_oneplus_hotdog/commits/eos-q)\n"
  connection: local
  when: EOS_RELEASE_TYPE != "CUSTOM"

- set_fact:
    dl_links: |-
        ***Download:*** [{{ BUILDIDENT }} \- rooted]({{ leech_server }}/e-os/a10_rooted/{{ target_model }})
    keysdir: '/home/androidsource/do-not-touch/KEYS/{{ android_shortversion }}_{{ target_model }}_rooted'
    rempath: "/home/nightlies/roms/e-os/a10_rooted/{{ target_model }}"
  connection: local
  when: PREROOT_BOOT == "true"

- set_fact:
    keysdir: '/home/androidsource/do-not-touch/KEYS/{{ android_shortversion }}_{{ target_model }}'
    rempath: "/home/nightlies/roms/e-os/a10/{{ target_model }}/"
  connection: local
  when: PREROOT_BOOT != "true"
