---

- include_tasks: ../../../common/tasks/clean.yml
  vars:
    override_reset_git: false

- name: "Specific DOS -basic- cleanup"
  file:
    path: "{{ item }}"
    state: absent
  loop:
    - "{{ SRCPATH }}/out/target/product/{{ target_model }}/rec_tmp"

- name: "Specific DOS -full- cleanup"
  file:
    path: "{{ item }}"
    state: absent
  loop:
    - "{{ SRCPATH }}/packages/apps/Fennec_DOS-Shim"
    - "{{ SRCPATH }}/vendor/divested"
    - "{{ SRCPATH }}/vendor/fdroid_prebuilt"
    - "{{ SRCPATH }}/packages/apps/SupportDivestOS"
  when: 
     - (override_reset_git == "undef" and reset_git == "true") or (override_reset_git == "true") or (override_sync == "true")

- name: "reset workspace (by DOS)"
  shell: |
    source ../../Scripts/init.sh  && echo "sourcing init: success" \
      && repo forall -c 'git am --abort; git revert --abort' || true \
      && resetWorkspace >> {{ BUILD_LOG }} 2>&1
  register: resetout
  #failed_when: "'No error detected' not in resetout.stdout"
  environment:
    BDEVICE: "{{ target_model }}"
    PATH: "{{ BUILDHOME }}/.yarn/bin:{{ BUILDHOME }}/.config/yarn/global/node_modules/.bin:{{ BUILDHOME }}/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
  args:
    chdir: "{{ SRCPATH }}"
    executable: "{{ BUILDHOME }}/.local/bin/sh"
