---

- include: ../../common/tasks/clean.yml

- name: "Specific DOS cleanup"
  file:
    path: "{{ item }}"
    state: absent
  loop:
    - packages/apps/Fennec_DOS-Shim
    - vendor/divested
    - vendor/fdroid_prebuilt
    - packages/apps/SupportDivestOS
