---

- name: "Specific DOS basic cleanup"
  file:
    path: "{{ item }}"
    state: absent
  loop:
    - "{{ SRCPATH }}/packages/apps/Fennec_DOS-Shim"
    - "{{ SRCPATH }}/vendor/divested"
    - "{{ SRCPATH }}/vendor/fdroid_prebuilt"
    - "{{ SRCPATH }}/packages/apps/SupportDivestOS"
    - "{{ SRCPATH }}/out/target/product/{{ target_model }}/rec_tmp"
