---

- include: clean.yml
- include: vars.yml

- block:

  - include: sync.yml
  - include: selinux_permissive.yml
    when: 
      - xos_permissive is defined and xos_permissive | bool

  when:
    - (override_reset_git == "undef" and reset_git == "true") or (override_reset_git == "true") or (override_sync == "true")
