---

- name: sync DOS
  shell: |
    git reset --hard
    git checkout {{ xos_main_branch | d(default_xos_main_branch) }}
    git pull
    git submodule update --init --recursive
  args:
    chdir: "{{ DOSPATH }}"
    executable: /bin/bash

# sync LOS etc
- include_tasks: ../../../common/tasks/sync.yml

- name: "apply DOS patches"
  shell: |
    source ../../Scripts/init.sh  && echo "sourcing init: success" \
      && patchWorkspace >> {{ BUILD_LOG }} 2>&1
    awk -i inplace '!/enforce-product-packages-exist-internal/' vendor/lineage/config/common.mk
  register: patchout
  failed_when: "'No error detected' not in patchout.stdout"
  environment:
    BDEVICE: "{{ target_model }}"
    PATH: "{{ BUILDHOME }}/.yarn/bin:{{ BUILDHOME }}/.config/yarn/global/node_modules/.bin:{{ BUILDHOME }}/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
  args:
    chdir: "{{ SRCPATH }}"
    executable: "{{ BUILDHOME }}/.local/bin/sh"
