---

- name: sync DOS
  shell: |
    git reset --hard
    git checkout {{ xos_main_branch | d(default_xos_main_branch) }}
    git pull
    git submodule update --init --recursive
  args:
    chdir: "{{ DOSPATH }}"
    executable: /bin/bash

# sync LOS etc
- include_tasks: ../../../common/tasks/sync.yml

- name: "apply DOS patches"
  shell: |
    source $HOME/.bashrc && echo "source1 success"
    source ../../Scripts/init.sh  && echo "source2 success" && patchWorkspace
    awk -i inplace '!/enforce-product-packages-exist-internal/' vendor/lineage/config/common.mk
  environment:
    BDEVICE: "{{ target_model }}"
  args:
    chdir: "{{ SRCPATH }}"
    executable: /bin/bash

- fail:
    msg: boooooo
