---
# human readable model name
target_model_full: "Samsung J5 - 2017"

# boot debugger path & config
extendrom_debug_path_default: /cache
extendrom_debug_path_size_full_default: 500 
extendrom_debug_path_size_kernel_default: 100
extendrom_debug_path_size_selinux_default: 200
extendrom_debug_path_size_crash_default: 200

# extend extendrom_package_list
extendrom_package_list: "{{ extendrom_package_list_default }} opencamera_j5_latest"

# common defaults overrides
vbmeta_verify: false

# enable kernel patching
divest_unsupported_device: true

dtree_cl: |-
  \- device tree: [commits](https://github.com/AXP-OS/device_samsung_j5y17lte/commits/{{ build_tag }})

cdtree_cl: |-
  \- common tree: [commits](https://github.com/AXP-OS/device_samsung_exynos7870-common/commits/{{ build_tag }}})

kernel_cl: |-
  \- Kernel: [commits](https://github.com/AXP-OS/android_kernel_samsung_exynos7870/commits/{{ build_tag }})
