---

- name: Ensure a previous build script is gone
  file:
    path: "build_{{ target_model }}_{{ android_shortversion }}_{{ ROM_FLAVOR }}.sh"
    state: absent

- name: Upload build script
  template:
    src: build.sh.j2
    dest: "build_{{ target_model }}_{{ android_shortversion }}_{{ ROM_FLAVOR }}.sh"
    mode: 0700

- name: "Set device vars"
  template:
    src: divested.vars.j2
    dest: ".divested.vars.{{ target_model }}"
