---

- include: ../../common/tasks/setvars.yml
- include: ../../common/tasks/clean.yml

- include: ../../common/tasks/sync.yml
  when:
    - (override_reset_git == "undef" and reset_git == "true") or (override_reset_git == "true") or (override_sync == "true")

- include: ../../../common/tasks/secpatch.yml
- include: copy.yml
