---

- debug:
    var: semaphore_vars

- set_fact:
    PIPETWRPBUILDVER: "{{ shrp_release_type | d('PREVIEW') }}-{{ semaphore_vars.task_details['target_version'] }}"

- debug:
    msg: "SHRP version/buildid has been set to: {{ PIPETWRPBUILDVER }}"
