---

- include: ../../common/tasks/setvars.yml
- include: setvars.yml

- include: ../../common/tasks/clean.yml

- include: ../../common/tasks/sync.yml
  when:
    - (override_reset_git == "undef" and reset_git == "true") or (override_reset_git == "true") or (override_sync == "true")

- include: fetch_recovery.yml

- include: patch.yml
  when: 
    - EOS_RELEASE_TYPE == "CUSTOM"
    - (override_reset_git == "undef" and reset_git == "true") or (override_reset_git == "true")

- include: copy.yml
