---

- name: "Start Semaphore task(s)"
  ansible.builtin.uri:
    url: "{{ semaphore_api_uri }}/project/{{ semaphore_project_id }}/tasks"
    method: POST
    headers:
        Content-Type: application/json
        Authorization: "Bearer {{ vault_semaphore_api_rw }}"
    body_format: json
    body: |
        { 
          "debug": true,
          "dry_run": true,
          "environment": "{ \"debug_build\":\"{{ item.debug_build | d(True) }}\", \"post_cleanup\":\"{{ item.post_cleanup | d(True) }}\", \"unstable_build\":\"{{ item.unstable_build | d(True) }}\",  }",
          "template_id": {{ item.tid }}
        }
    status_code: [ 201, 200 ]
  register: tmpltask
  changed_when: tmpltask.status == 201
  #no_log: True
  # the following list also indicates the order in which a full build run will be done
  loop:
#    - { tid: 105 } # cheetah
    - { tid: 109 } # lynx
    - { tid: 103 } # bluejay
#    - { tid: 84 } # hotdog
#    - { tid: 87 } # fajita
#    - { tid: 86 } # j5y17lte
#    - { tid: 113, debug_build: False, unstable_build: False  } # xz2c
#    - { tid: 102, debug_build: False, unstable_build: False  } # hotdogb
#    - { tid: 111, debug_build: False, unstable_build: False } # oriole
#    - { tid: 100, debug_build: False, unstable_build: False } # sunfish
