---

os_name: "AXP.OS" 

# git
git_repo_main_manifests: "https://github.com/LineageOS/android.git"

# DOS repo + main branch
axp_git_repo: "git@github.com:sfX-android/build_divestos.git"
default_axp_main_branch: '2023-07-14'
git_repo_local_manifests_branch: "{{ ROM_FLAVOR }}-{{ android_shortversion }}"

# build vars
los_version: "{{ android_shortversion | replace('a13','20.0') | replace('a12','19.1') | replace('a9','16.0') }}"
git_repo_main_branch: "lineage-{{ los_version }}"
DOSPATH: "/home/androidsource/do-not-touch/{{ ROM_FLAVOR }}"
SRCPATH: "{{ DOSPATH }}/Build/LineageOS-{{ los_version }}"
axp_finalzip_dir: "{{ ZIPDIR }}/LineageOS-{{ los_version }}/release_keys/"
USE_CCACHE: 1
CCACHE_DIR: "/ssd/ccache/jenkins/{{ android_shortversion }}"
rempath: "/home/nightlies/roms/{{ ROM_FLAVOR }}/{{ android_shortversion }}/{{ target_model }}/"
RELEASE_TYPE: dos
ROM_VERSION: "{{ build_id }}"
PREFIXFNAME: "{{ os_name }}-{{ los_version }}"
skip_gen_checksum: true

# extendrom stuff
use_extendrom: "true"
extendrom_package_list: "additional_repos.xml Phonesky Lawnchair-latest SignMagisk AuroraServices AuroraStore MicrogGmsCore GsfProxy"

# keys
KEYS_CN: "{{ os_name }}"
KEYS_SIZE: 8192
KEYS_HASHTYPE: sha512
keysdir: "{{ DOSPATH }}/Signing_Keys/4096pro/{{ target_model }}/"

# notification vars
ota_hint: |-
  ***OTA Update:*** supported

rom_cl: |-
  ***Changes:***
  \- divestOS: [Changelog](https://divestos.org/pages/news)
  \- X\.OS: [Changelog](https://axp.binbash.rocks/news.html)

dl_links: |-
  ***Download:*** [{{ ROMFILE.stdout | regex_escape() }} ]({{ leech_server }}/{{ ROM_FLAVOR }}/{{ android_shortversion }}/{{ target_model }})

device_cl: |-
  ***{{ target_model_full | regex_escape() }}*** ***\({{ target_model | regex_escape() }}\)*** \- ***{{ ROM_FLAVOR | regex_escape() }}***
