---

- name: "Build {{ target_model }}"
  hosts: buildserver
  gather_facts: false

  vars_files:
    - ../roles/common/vars/main.yml

  tasks:
    - block:
      - include_role:
          name: "{{ ROM_FLAVOR }}/{{ target_model }}_{{ android_shortversion }}"
      - include_role:
          name: build_rom
      always:
      - include_role:
          name: notify
