---

- name: "Build {{ target_model }}"
  hosts: buildserver
  gather_facts: false

  vars_files:
    - ../roles/common/vars/main.yml

  vars:
    tg_success: |
        {{ ICON_GOOD }} New build _*{{ BUILDIDENT }}*_ has finished SUCCESSFULLY!

        \- Device: ***{{ BDEVICE }}***
        \- ROM: {{ ROM_FLAVOR }} {{ android_shortversion | replace("-","\-") | replace(".","\.") }}

        {{ rom_cl }}
        {{ kernel_cl }}
        {{ dtree_cl }}
        {{ cdtree_cl }}
        {{ dl_links }}
        SHA256:
        {{ hash.stat.checksum }}

        {{ ota_hint }}
        
        This build has been created by [Ansible](https://github.com/sfX-android/automation_scripts) + [Semaphore](https://ansible-semaphore.com) with <3 

    tg_failed: |
        {{ ICON_BAD }} ***ERROR:*** Last build failed\!

        \- ROM: {{ ROM_FLAVOR }} {{ android_shortversion | replace("-","\-") | replace(".","\.") }}
        \- Device: ***{{ BDEVICE }}***
        \- Build id: _{{ BUILDIDENT | replace("-","\-") }}_

  tasks:
    # https://docs.ansible.com/ansible/latest/user_guide/playbooks_blocks.html
    - block:
      - import_role:
          name: "{{ ROM_FLAVOR }}/{{ target_model }}_{{ android_shortversion }}"
      - import_role:
          name: build_rom
      rescue:
        - set_fact:
            tg_group_id: "{{ vault_tg_group_id_failing }}"
            tg_output: "{{ tg_failed }}"
        - include_role:
            name: notify
        - fail:
            msg: "build failure occured. check log."

- name: "Release {{ ROM_FLAVOR}} for {{ target_model }}"
  hosts: leech
  gather_facts: false

  vars_files:
    - ../roles/common/vars/main.yml

  tasks:
    # https://docs.ansible.com/ansible/latest/user_guide/playbooks_blocks.html
    - block:
      - import_role:
          name: release_rom
      - set_fact:
          tg_group_id: "{{ vault_tg_group_id_failing }}"
          #tg_group_id: "{{ vault_tg_group_id_automation }}"
          tg_output: "{{ tg_success }}"
      - import_role:
          name: notify
      rescue:
        - set_fact:
            tg_group_id: "{{ vault_tg_group_id_failing }}"
            tg_output: "{{ tg_failed }}"
        - include_role:
            name: notify
        - fail:
            msg: "release-build failure occured. check log."
      when:
        - (override_release_build is undefined and release_build == "true") or (override_release_build is defined and override_release_build == "true")
