---

- name: "Build {{ target_model }}"
  hosts: buildserver
  gather_facts: false

  vars_files:
    - ../roles/common/vars/main.yml

  roles:
    - "{{ ROM_FLAVOR }}/{{ target_model }}_{{ android_shortversion }}"
    - build_rom
