---

- name: "Build {{ target_model }}"
  hosts: buildserver
  gather_facts: false
 
#  tasks:
#    - name: "test"
#      debug:
#        msg: "hi"
        
  roles:
    - {{ target_model }}_{{ android_shortversion }}
