---

- name: "Build {{ target_model }}"
  hosts: buildserver
  gather_facts: false

  vars_files:
    - ../roles/common/vars/main.yml

  tasks:
    # https://docs.ansible.com/ansible/latest/user_guide/playbooks_blocks.html
    - block:
      - import_role:
          name: "{{ ROM_FLAVOR }}/{{ target_model }}_{{ android_shortversion }}"
      - import_role:
          name: build_rom
      - import_role:
          name: release_rom
      - set_fact:
          tg_group_id: "{{ vault_tg_group_id_failing }}"
          #tg_group_id: "{{ vault_tg_group_id_automation }}"
          tg_output: |
                {{ ICON_GOOD }} New build _*{{ BUILDIDENT }}*_ has finished SUCCESSFULLY!
                
                \- Device: ***{{ BDEVICE }}***
                \- ROM: {{ ROM_FLAVOR }}-{{ android_shortversion }}
                
                {{ rom_cl }}
                {{ kernel_cl }}
                {{ dtree_cl }}
                {{ cdtree_cl }}
                {{ dl_links }}
                SHA256:
                {{ hash.stat.checksum }}
                
                {{ ota_hint }}
      - import_role:
          name: notify
      rescue:
        - set_fact:
            tg_group_id: "{{ vault_tg_group_id_failing }}"
            tg_output: |
                {{ ICON_BAD }} ***ERROR:*** Last build failed\!
                
                \- ROM: {{ ROM_FLAVOR | replace("-","\-") | replace("\.","\.") }}-{{ android_shortversion | replace("-","\-") | replace("\.","\.") }}
                \- Device: ***{{ BDEVICE }}***
                \- Build id: _{{ BUILDIDENT | replace("-","\-") }}_
        - include_role:
            name: notify
        - fail:
            msg: "build failure occured. check log."
