---

- name: "Build {{ target_model }}"
  hosts: buildserver
  gather_facts: true

  pre_tasks:
    - debug:
        msg: "{{ semaphore_vars }}"
          
    - set_fact:
        semaphore_runfile: "{{ semaphore_lock_dir }}/{{ ROM_FLAVOR }}_{{ target_model }}_{{ build_id }}.ansible_running"

    - name: "set semaphore running indicator"
      connection: local
      copy:
        dest: "{{ semaphore_runfile }}"
        content: |
          date="{{ ansible_date_time.iso8601 }}"
          play=build.yml
          target={{ target_model }}
          role="{{ ROM_FLAVOR }}/{{ target_model }}"
          
  tasks:
    # https://docs.ansible.com/ansible/latest/user_guide/playbooks_blocks.html
    - block:
    
      - import_role:
          name: common

      - include_role:
          name: eos/common
          public: yes
        when: ROM_FLAVOR == "eos"

      - include_role:
          name: graphene/common
          public: yes
        when: ROM_FLAVOR == "graphene"

      - debug:
          var: vault_tg_group_id_failing

      - fail:
          msg: "boo.. vault_tg_group_id_failing is undefined"
        when: vault_tg_group_id_failing is undefined

      - import_role:
          name: pre
          
      - include_vars: "../roles/{{ ROM_FLAVOR }}/all/vars/{{ target_model }}.yml"
        when: 
          - ROM_FLAVOR == "SHRP" or ROM_FLAVOR == "TWRP"

      - import_role:
          name: "roles/{{ ROM_FLAVOR }}/{{ target_model }}"

      - import_role:
          name: build_rom

      - import_role:
          name: release
        when:
          - (override_release_build == "undef" and release_build == "true") or (override_release_build == "true")

      - set_fact:
          tg_group_id: "{{ vault_tg_group_id_automation }}"
        when: debug_build is not defined or (debug_build is defined and debug_build == "false")

      - set_fact:
          tg_group_id: "{{ vault_tg_group_id_failing }}"
        when: debug_build is defined and debug_build == "true"

      - import_role:
          name: notify

      - name: "remove semaphore running indicator"
        connection: local
        file:
          path: "{{ semaphore_runfile }}"
          state: absent

      - import_role:
          name: post

      # when any of the above fails notify always 
      rescue:
        - import_role:
            name: post

        - set_fact:
            tg_group_id: "{{ vault_tg_group_id_failing }}"

        - import_role:
            name: notify

        - name: "remove semaphore running indicator"
          connection: local
          file:
            path: "{{ semaphore_runfile }}"
            state: absent
            
        - fail:
            msg: "build failure occured. check log."
