---

- name: "Build {{ target_model }}"
  hosts: buildserver
  gather_facts: false

  vars_files:
    - ../roles/common/vars/main.yml

  tasks:
    # https://docs.ansible.com/ansible/latest/user_guide/playbooks_blocks.html
    - block:
      - include_role:
          name: "{{ ROM_FLAVOR }}/{{ target_model }}_{{ android_shortversion }}"
      - include_role:
          name: build_rom
      - set_fact:
          tg_group_id: "{{ vault_tg_group_id_failing }}"
          #tg_group_id: "{{ vault_tg_group_id_automation }}"
          tg_output: '{{ ICON_GOOD }} New build _*{{ BUILDIDENT }}*_ has finished SUCCESSFULLY!\n\n{{ rom_cl }}{{ kernel_cl }}{{ dtree_cl }}{{ cdtree_cl }}{{ dl_links }}\nSHA256:\n{{ hash }}\n{{ ota_hint }}'
      - include_role:
          name: notify
      rescue:
        - set_fact:
            tg_group_id: "{{ vault_tg_group_id_failing }}"
            tg_output: '{{ ICON_BAD }} ***ERROR:*** Last build failed ***!\n\n- Device: ***{{ BDEVICE }}***\n- Build id: _{{ BUILDIDENT }}_\n- Log: [console link](${BUILD_URL}/console)'
        - include_role:
            name: notify
