---

- name: "Debug"
  hosts: buildserver
  gather_facts: true
      
  tasks:
    - debug:
        var: semaphore_vars

    - import_role:
        name: eos/common
      when: ROM_FLAVOR == "eos"

    - import_role:
        name: graphene/common
      when: ROM_FLAVOR == "graphene"

    - debug:
         var: SEPARATE_OUT_DIR

    - import_role:
        name: common
  
    - name: "Telegram TEST notify"
      connection: local
      community.general.telegram:
        token: "{{ vault_tg_token }}"
        api_args:
          chat_id: "{{ vault_tg_group_id_failing }}"
          parse_mode: "MarkdownV2"
          text: "DEBUG playbook ended successfully"
          disable_web_page_preview: True
