---

- name: "Debug"
  hosts: buildserver
  gather_facts: true
      
  tasks:
    - debug:
        var: semaphore_vars
        
    #- debug:
    #    var: ansible_facts

    - import_role:
        name: common

    - include_role:
        name: eos/common
        public: yes
      when: ROM_FLAVOR == "eos"

    - include_role:
        name: graphene/common
        public: yes
      when: ROM_FLAVOR == "graphene"

    - debug:
         var: git_repo_main_manifests

    - debug:
         var: SRCPATH
  
    - set_fact:
        semaphore_runfile: "{{ semaphore_lock_dir }}/{{ ROM_FLAVOR }}_{{ semaphore_vars.task_details.target_version }}.ansible_running"

    - name: "set semaphore running indicator"
      connection: local
      copy:
        dest: "{{ semaphore_runfile }}"
        content: |
          date="{{ ansible_date_time.iso8601 }}"
          play=debug.yml
          role="{{ ROM_FLAVOR }}"
  
    - name: "Telegram TEST notify"
      connection: local
      community.general.telegram:
        token: "{{ vault_tg_token }}"
        api_args:
          chat_id: "{{ vault_tg_group_id_failing }}"
          parse_mode: "MarkdownV2"
          text: "DEBUG playbook ended successfully"
          disable_web_page_preview: True
