---

- name: "Debug"
  hosts: buildserver
  gather_facts: true
      
  tasks:
    - debug:
        var: semaphore_vars

    - import_role:
        name: common

    - set_fact:
        SECPATCH_DATE: "2022-08"
        sec_patch_topics: >-
          topic:P_asb_2022-02 OR
          topic:P_asb_2022-03 OR
          topic:P_asb_2022-04 OR
          topic:P_asb_2022-05 OR
          topic:P_asb_2022-06 OR
          topic:P_asb_2022-07 OR
          topic:P_asb_2022-08
    - name: "Create repopick list (required on eOS to find path names)"
      shell: "/usr/bin/python3.6 external/cherrypicker/scripts/cherrypicker.py -R los -B lineage-16.0 -Q '{{ sec_patch_topics }}' | grep --color=never https | iconv -t utf-8"
      args:
        chdir: "{{ SRCPATH }}"
      register: picklist

    - debug: 
        var: picklist.stdout_lines
      
    - name: "Telegram TEST notify"
      connection: local
      community.general.telegram:
        token: "{{ vault_tg_token }}"
        api_args:
          chat_id: "{{ vault_tg_group_id_failing }}"
          parse_mode: "MarkdownV2"
          text: "This is a test"
          disable_web_page_preview: True
