---

- name: "Debug"
  hosts: buildserver
  gather_facts: true
  
  vars_files:
    - ../roles/common/vars/main.yml
    
  tasks:
    - setup:
    - debug: var=vars
    - debug: var=hostvars[inventory_hostname]

- name: "Debug2"
  hosts: leech
  gather_facts: false
    
  tasks:
    - debug: var=vars
    - debug: var=hostvars[inventory_hostname]
