---

- name: "Debug"
  hosts: buildserver
  gather_facts: true
  
  vars_files:
    - ../roles/common/vars/main.yml
    
  tasks:
    - setup:
    - debug: var=vars
    - debug: var=hostvars[inventory_hostname]
