---

- name: "Debug"
  hosts: buildserver
  gather_facts: true
      
  tasks:
    - import_role:
        name: common
#    - debug: var=vars
#    - debug: var=hostvars[inventory_hostname]

- name: "Debug2"
  hosts: leech
  gather_facts: false
    
  tasks:
    - debug:
        var: vars[groups]
