---

- name: "Sharing debug logs"
  become: no
  hosts: buildserver
  gather_facts: false
      
  tasks:
    
    - name: gather needed facts
      connection: local
      ansible.builtin.setup:

    - include_role:
        name: common
        tasks_from: justvault.yml
        public: yes

    - name: paste ansible log
      connection: local
      shell: >-
        gist-paste --private  -d "ANSIBLE LOG - {{ ansible_facts['date_time']['iso8601'] }}" -f ansible.log.{{ ansible_facts['date_time']['iso8601'] }}.yaml  {{ lookup('ansible.builtin.ini', 'log_path', section='defaults',  file=ansible_config_file) }}
      register: paste_ansible

    - name: Fetch build log
      fetch:
        src: "build_{{ target_model }}_{{ android_shortversion }}_{{ ROM_FLAVOR }}.log"
        dest: /tmp/

    - name: paste build log
      connection: local
      shell: >-
        gist-paste --private  -d "BUILD LOG - {{ ansible_facts['date_time']['iso8601'] }}" -f build.log.{{ ansible_facts['date_time']['iso8601'] }}.sh /tmp/{{ inventory_hostname }}/build_{{ target_model }}_{{ android_shortversion }}_{{ ROM_FLAVOR }}.log
      register: paste_build

    - name: "Print generated links"
      connection: local
      debug:
        msg: |
          Please share the following links:
          
          - ansible: {{ paste_ansible.stdout }}
          - build: {{ paste_build.stdout }}
    
    - name: "Telegram notify"
      connection: local
      community.general.telegram:
        token: "{{ vault_tg_token }}"
        api_args:
          chat_id: "{{ vault_tg_group_id_failing }}"
          parse_mode: "MarkdownV2"
          text: |
            Debug logs uploaded:
          
            \- ansible: [log]({{ paste_ansible.stdout }})
            \- build: [log]({{ paste_build.stdout }})
          disable_web_page_preview: True
      when: telegram_notifications | bool
