---

- name: "Sharing debug logs"
  become: no
  hosts: buildserver
  gather_facts: false
      
  tasks:
    
    - ansible.builtin.setup:
        filter:
          - ansible_date_time
          - ansible_config_file

    - include_role:
        name: common
        tasks_from: empty.yml
        public: yes

    - name: paste ansible log
      connection: local
      shell: >-
        pwd;
        gist-paste --private  -d "ANSIBLE LOG - {{ ansible_date_time.iso8601 }}" -f ansible.log.{{ ansible_date_time.epoch }}.yaml  {{ lookup('ansible.builtin.ini', 'log_path', section='defaults',  file=ansible_config_file) }}
      register: paste_ansible
      when: dontskipme is defined

    - name: Fetch build log
      fetch:
        src: "build_{{ target_model }}_{{ android_shortversion }}_{{ ROM_FLAVOR }}.log"
        dest: /tmp/

    - name: paste build log
      connection: local
      shell: >-
        gist-paste --private  -d "BUILD LOG - {{ ansible_date_time.iso8601 }}" -f build.log.{{ ansible_date_time.epoch }}.sh /tmp/{{ inventory_hostname }}/build_{{ target_model }}_{{ android_shortversion }}_{{ ROM_FLAVOR }}.log
      register: paste_build

    - set_fact:
        output: |
          Please share the following links:
          
          - ansible: [log]({{ paste_ansible.stdout }})
          - build: [log]({{ paste_build.stdout }})

    - name: Print
      connection: local
      debug:
        msg: "{{ output }}"
    
    - name: "Telegram notify"
      connection: local
      community.general.telegram:
        token: "{{ vault_tg_token }}"
        api_args:
          chat_id: "{{ vault_tg_group_id_failing }}"
          parse_mode: "MarkdownV2"
          text: "{{ output | regex_escape() }}"
          disable_web_page_preview: True
      when: telegram_notifications | bool
