---

- include: ../../common/tasks/setvars.yml

- include: ../../common/tasks/clean.yml

- include: set_buildid.yml

- include: set_local_manifest.yml

- include: ../../common/tasks/sync.yml
  when:
    - (override_reset_git == "undef" and reset_git == "true") or (override_reset_git == "true") or (override_sync == "true")

- include: sync.yml
  when:
    - (override_reset_git == "undef" and reset_git == "true") or (override_reset_git == "true") or (override_sync == "true")

- include: patch.yml
  when: 
    - (override_reset_git == "undef" and reset_git == "true") or (override_reset_git == "true")

- include: copy.yml
