---

- debug:
    var: semaphore_vars

- set_fact:
    PIPETWRPBUILDVER: "{{ RELEASE_TYPE }}-{{ semaphore_vars.task_details['target_version'] }}"

- debug:
    msg: "TWRP version/buildid has been set to: {{ PIPETWRPBUILDVER }}"
