---

- name: "Stopping service {{ blocking_service_name }} on {{ blocking_service_host }}"
  remote_user: "{{ blocking_service_ssh_user }}"
  become: yes
  service:
    name: "{{ blocking_service_name }}"
    state: stopped
  delegate_to: "{{ blocking_service_host }}"
  no_log: true
