---

- name: "Stopping service {{ blocking_service_name }} on {{ blocking_service_host }}"
  service:
    name: "{{ blocking_service_name }}"
    state: stopped
  delegate_to: "{{ blocking_service_host }}"
