---

- name: "Read Security patch date"
  shell: |-
    grep -E 'PLATFORM_SECURITY_PATCH\s+:=\s+' build/core/version_defaults.mk| cut -d "=" -f 2 | tr -d " " | tail -n1
  args:
    chdir: "{{ SRCPATH }}"
    executable: /bin/bash
  register: sec_level_date
  when: ROM_FLAVOR != "graphene"
  
- name: "Read Security patch date (gOS)"
  shell: |-
    find build/release/build_config/ -type f -name '*.scl' ! -name trunk_versions.scl -exec grep RELEASE_PLATFORM_SECURITY_PATCH {} \; | cut -d '"' -f4
  args:
    chdir: "{{ SRCPATH }}"
    executable: /bin/bash
  register: sec_level_date
  when: ROM_FLAVOR == "graphene"
