---

- name: "Read Security patch date"
  shell: |-
    grep -E 'PLATFORM_SECURITY_PATCH\s+:=\s+' build/core/version_defaults.mk| cut -d "=" -f 2 | tr -d " " | tail -n1
  args:
    chdir: "{{ SRCPATH }}"
    executable: /bin/bash
  register: sec_level_date_los
  when: ROM_FLAVOR != "graphene"
  
- name: "Read Security patch date (gOS)"
  shell: |-
    find build/release/build_config/ -type f -name '*.scl' ! -name trunk_versions.scl -exec grep RELEASE_PLATFORM_SECURITY_PATCH {} \; | cut -d '"' -f4
  args:
    chdir: "{{ SRCPATH }}"
    executable: /bin/bash
  register: sec_level_date_gos
  when: ROM_FLAVOR == "graphene"

- ansible.builtin.set_fact:
    sec_level_date: "{% if sec_level_date_los.stdout is defined %}{{ sec_level_date_los.stdout }}{% else %}{{ sec_level_date_gos.stdout }}{% endif %}"
  when: sec_level_date_los.stdout is defined or sec_level_date_gos.stdout is defined
