---

- include_tasks: get_secpatchlevel.yml
  when: 
    - ROM_FLAVOR != "MAID"
    - ROM_FLAVOR != "TWRP"
    - ROM_FLAVOR != "SHRP"
    - sec_level_date.stdout is undefined
    - buildresult.rc is defined and buildresult.rc == 0

- include_tasks: telegram.yml
  when: telegram_notifications | bool
