---
# doc: https://core.telegram.org/bots/api

- name: "Telegram: Summary (success)"
  connection: local
  community.general.telegram:
    token: "{{ vault_tg_token }}"
    api_args:
      chat_id: "{{ tg_group_id }}"
      parse_mode: "MarkdownV2"
      text: "{{ tg_success }}"
      disable_web_page_preview: True
  when: ansible_failed_result is undefined

- name: "Telegram: Summary (failed)"
  connection: local
  community.general.telegram:
    token: "{{ vault_tg_token }}"
    api_args:
      chat_id: "{{ tg_group_id }}"
      parse_mode: "MarkdownV2"
      text: "{{ tg_failed }}"
      disable_web_page_preview: True
  when: ansible_failed_result is defined

- stat:
    path: "/tmp/{{ inventory_hostname }}/build_{{ target_model }}_{{ android_shortversion }}_{{ ROM_FLAVOR }}.log"
  register: logfile
  connection: local

- community.general.archive:
    path: "/tmp/{{ inventory_hostname }}/build_{{ target_model }}_{{ android_shortversion }}_{{ ROM_FLAVOR }}.log"
    dest: "/tmp/{{ inventory_hostname }}/build_{{ target_model }}_{{ android_shortversion }}_{{ ROM_FLAVOR }}.log.gz"
  when: logfile.stat.isreg is defined
  connection: local
    
- name: "Telegram: attach log (on errors)"
  connection: local
  shell: |
     curl -F document=@/tmp/{{ inventory_hostname }}/build_{{ target_model }}_{{ android_shortversion }}_{{ ROM_FLAVOR }}.log.gz \ 
     -H "Content-Type:multipart/form-data" \ 
     "https://api.telegram.org/bot{{ vault_tg_token }}/sendDocument?chat_id={{ tg_group_id }}"
  when: 
    - buildresult.rc is undefined or buildresult.rc != 0
    - tg_group_id == vault_tg_group_id_failing
    - logfile.stat.isreg is defined
    - ansible_failed_result is defined
  no_log: true

# uploading via multipart/form-data seems to not work
# https://core.telegram.org/bots/api#senddocument
#- name: "Telegram: attach log (on errors)"
#  connection: local
#  community.general.telegram:
#    token: "{{ vault_tg_token }}"
#    api_method: sendDocument
#    api_args:
#      chat_id: "{{ tg_group_id }}"
#      document: "/tmp/build_{{ target_model }}_{{ android_shortversion }}_{{ ROM_FLAVOR }}.log"
#  when: 
#    - buildresult.rc is undefined or buildresult.rc != 0
#    - tg_group_id == vault_tg_group_id_failing
#    - logfile.stat.isreg is defined

# works BUT file content will always be base64 encoded, see:
# https://github.com/ansible/ansible/issues/73621#issuecomment-780650153
#- name: "Telegram: attach log (on errors)"
#  connection: local
#  uri:
#    url: https://api.telegram.org/bot{{ vault_tg_token }}/sendDocument
#    method: POST
#    body_format: form-multipart
#    body:
#      chat_id: "{{ tg_group_id }}"
#      document:
#        filename: "/tmp/build_{{ target_model }}_{{ android_shortversion }}_{{ ROM_FLAVOR }}.log"
#        mime_type: text/plain
#  when: 
#    - buildresult.rc is undefined or buildresult.rc != 0
#    - tg_group_id == vault_tg_group_id_failing
#    - logfile.stat.isreg is defined
