---
# doc: https://core.telegram.org/bots/api

- name: "Telegram: Summary"
  connection: local
  community.general.telegram:
    token: "{{ vault_tg_token }}"
    api_args:
      chat_id: "{{ tg_group_id }}"
      parse_mode: "MarkdownV2"
      text: "{{ tg_output }}"
      disable_web_page_preview: True

- stat:
    path: "/tmp/build_{{ target_model }}_{{ android_shortversion }}_{{ ROM_FLAVOR }}.log"
  register: logfile
  connection: local
 
- name: "Telegram: attach log (on errors)"
  connection: local
  community.general.telegram:
    token: "{{ vault_tg_token }}"
    api_args:
      chat_id: "{{ tg_group_id }}"
      text: 'build_{{ target_model | replace("(-|.)","\\\1") }}_{{ android_shortversion | replace("(-|.)","\\\1") }}_{{ ROM_FLAVOR | replace("(-|.)","\\\1") }}\.log'
      document: "/tmp/build_{{ target_model }}_{{ android_shortversion }}_{{ ROM_FLAVOR }}.log"
      disable_web_page_preview: True
      parse_mode: "MarkdownV2"
  when: 
    - buildresult.rc is undefined or buildresult.rc != 0
    - tg_group_id == vault_tg_group_id_failing
    - logfile.stat.isreg is defined
