---
# doc: https://core.telegram.org/bots/api

- name: "Telegram: Summary"
  connection: local
  community.general.telegram:
    token: "{{ vault_tg_token }}"
    api_args:
      chat_id: "{{ tg_group_id }}"
      parse_mode: "MarkdownV2"
      text: "{{ tg_output }}"
      disable_web_page_preview: True

- stat:
    path: "/tmp/build_{{ target_model }}_{{ android_shortversion }}_{{ ROM_FLAVOR }}.log"
  register: logfile
  connection: local

# uploading via multipart/form-data seems to not work
# https://core.telegram.org/bots/api#senddocument
#- name: "Telegram: attach log (on errors)"
#  connection: local
#  community.general.telegram:
#    token: "{{ vault_tg_token }}"
#    api_method: sendDocument
#    api_args:
#      chat_id: "{{ tg_group_id }}"
#      document: "/tmp/build_{{ target_model }}_{{ android_shortversion }}_{{ ROM_FLAVOR }}.log"
#  when: 
#    - buildresult.rc is undefined or buildresult.rc != 0
#    - tg_group_id == vault_tg_group_id_failing
#    - logfile.stat.isreg is defined

- name: "Telegram: attach log (on errors)"
  connection: local
  uri:
    url: https://api.telegram.org/bot{{ vault_tg_token }}/sendDocument
    method: POST
    body_format: form-multipart
    headers:
      chat_id: "{{ tg_group_id }}"
    body:
        document: "/tmp/build_{{ target_model }}_{{ android_shortversion }}_{{ ROM_FLAVOR }}.log"
  when: 
    - buildresult.rc is undefined or buildresult.rc != 0
    - tg_group_id == vault_tg_group_id_failing
    - logfile.stat.isreg is defined
