---

- name: "Telegram: Summary"
  community.general.telegram:
    token: "{{ vault_tg_token }}"
    api_args:
      chat_id: "{{ tg_group_id }}"
      parse_mode: "MarkdownV2"
      text: "{{ tg_output }}"
      disable_web_page_preview: True

- name: "Telegram: attach log (on errors)"
  community.general.telegram:
    token: "{{ vault_tg_token }}"
    api_args:
      chat_id: "{{ tg_group_id }}"
      document: "/tmp/build_{{ target_model }}_{{ android_shortversion }}_{{ ROM_FLAVOR }}.log"
      disable_web_page_preview: True
      parse_mode: "MarkdownV2"
  when: 
    - buildresult.rc is undefined or buildresult.rc != 0
    - tg_group_id == vault_tg_group_id_failing
