---

# manifests
git_repo_local_manifests: "ssh://gitea@code.binbash.rocks:22227/secureOS/local_manifests.git"
git_repo_main_manifests: "https://github.com/GrapheneOS/platform_manifest.git"

ROM_VERSION: "{{ target_version }}"
# GOS_KERNEL_BRANCH:
# ROM_NAME:
# ROM_BL_TYPE:
# lunch_buildtype:

# notification vars
ota_hint: |-
  ***OTA Update:*** supported
device_cl: |-
  ***{{ target_model_full }}*** ***\({{ target_model | replace("-","\-") | replace("_","\_") }}\)*** \- ***{{ ROM_FLAVOR | replace("-","\-") }} {{ android_shortversion | replace("-","\-") | replace(".","\.") }}***
rom_cl: |-
  ***Changes:***
  \- LineageOS: [Changelog](https://grapheneos.org/releases#{{ target_mode }}-stable)
kernel_cl: |-
  \- kernel: [commits](https://github.com/GrapheneOS/kernel_common_5.10/commits/12.1)
dtree_cl: |-
  \- g4 unified tree: [commits](https://TBD/)
cdtree_cl: |-
  \- g4\-common tree: [commits](https://TBD/)
dl_links: |-
  ***Download:*** [{{ ROMFILE.stdout | replace("-","\-") | replace("_","\_") | replace(".","\.") }} ]({{ leech_server }}/{{ ROM_FLAVOR }}/{{ android_shortversion }}/{{ target_model }})

