---

- name: "Basic Clean-Up"
  file:
    state: absent
    path: "{{ SRCPATH }}/{{ item }}"
  loop:
    - build
    - device/
    - frameworks/av
    - frameworks/ml
    - frameworks/native
    - frameworks/support
    - hardware/marvell    
    - hardware/qcom/sm8150/
    - hardware/qcom-caf
    - hardware/qcom/Android.mk    
    - kernel/
    - packages/apps/Trebuchet
    - packages/apps/Updater
    - system/core
    - system/security
    - system/sepolicy
    - test/
    - vendor/lineage
    - vendor/fdroid
    - vendor/cm
    - vendor/nxp
    - .repo/local_manifests

- name: "Clean-Up out/ (1/2)"
  file:
    path: "{{ item }}"
  loop:
    - "{{ SRCPATH }}/out"
  when: clean_out is defined and clean_out == true
  
- name: "Clean-Up out/ (2/2)"
  file:
    path: "{{ item }}"
  loop:
    - "{{ SEPARATE_OUT_DIR }}"
  when: 
    - clean_out is defined and clean_out == true
    - SEPARATE_OUT_DIR is defined

- name: "Re-do out/ linking"
  file:
    src: "{{ SEPARATE_OUT_DIR }}"
    dest: "{{ SRCPATH }}/out"
    state: link
  when: 
    - clean_out is defined and clean_out == true
    - SEPARATE_OUT_DIR is defined

- name: "Reset state for all projects"
  shell: "{{ repo_bin }} forall -j{{ max_processes }} -vc 'git remote -v | head -n1; git reset --hard' || echo 'SKIPPING WITH ERRORCODE: $?'"
  args:
    chdir: "{{ SRCPATH }}"
