---

- name: "Basic Clean-Up (1/2)"
  file:
    state: absent
    path: "{{ SRCPATH }}/{{ item }}"
  loop:
    - build
    - device/
    - frameworks/av
    - frameworks/ml
    - frameworks/native
    - frameworks/support
    - hardware/marvell    
    - hardware/qcom/sm8150/
    - hardware/qcom-caf
    - hardware/qcom/Android.mk    
    - kernel/
    - packages/apps/Trebuchet
    - packages/apps/Updater
    - system/core
    - system/security
    - system/sepolicy
    - test/
    - vendor/lineage
    - vendor/fdroid
    - vendor/cm
    - vendor/nxp
    - .repo/local_manifests
  when: clean_basic is undefined or clean_basic == true

- name: "Basic Clean-Up (2/2)"
  shell: "find out -name {{ item }} -delete || true"
  loop:
    - build.prop
    - boot.img
    - recovery.img
    - blrecovery.img
  when: clean_out is undefined or clean_out == false

- name: "Clean-Up out/"
  file:
    path: "{{ SRCPATH }}/out"
    state: absent
  when: clean_out is defined and clean_out == true
  
- name: "Clean-Up out/ ({{ SEPARATE_OUT_DIR }})"
  file:
    path: "{{ SEPARATE_OUT_DIR }}"
    state: absent
  register: rm_other_out
  when: 
    - clean_out is defined and clean_out == true
    - SEPARATE_OUT_DIR is defined

- name: "Re-create out/ ({{ SEPARATE_OUT_DIR }})"
  file:
    path: "{{ SEPARATE_OUT_DIR }}"
    state: directory
  when: 
    - clean_out is defined and clean_out == true
    - SEPARATE_OUT_DIR is defined
    - rm_other_out.changed == true

- name: "Re-create out/ (link)"
  file:
    src: "{{ SEPARATE_OUT_DIR }}"
    dest: "{{ SRCPATH }}/out"
    state: link
  when: 
    - clean_out is defined and clean_out == true
    - SEPARATE_OUT_DIR is defined

- name: "Reset state for all projects"
  shell: "{{ repo_bin }} forall -j{{ max_processes }} -vc 'git remote -v | head -n1; git reset --hard' || echo 'SKIPPING WITH ERRORCODE: $?'"
  args:
    chdir: "{{ SRCPATH }}"
