---

- name: "Basic Clean-Up"
  file:
    state: absent
    path: "{{ SRCPATH }}/{{ item }}"
  loop:
    - device/
    - kernel/
    - vendor/lineage
    - vendor/fdroid
    - vendor/cm
    - vendor/nxp
    - hardware/qcom/sm8150/
    - hardware/qcom-caf
    - hardware/qcom/Android.mk
    - packages/apps/Trebuchet
    - hardware/marvell
    - frameworks/av
    - frameworks/native
    - frameworks/ml
    - packages/apps/Updater
    - system/core
    - system/sepolicy
    - build/make
    - system/security
    - test/
    - hardware/qcom/Android.mk

- name: "Clean-Up out/ (1/2)"
  file:
    path: "{{ item }}"
  loop:
    - "{{ SRCPATH }}/out"
  when: clean_out is defined and clean_out == true
  
- name: "Clean-Up out/ (2/2)"
  file:
    path: "{{ item }}"
  loop:
    - "{{ SEPARATE_OUT_DIR }}"
  when: 
    - clean_out is defined and clean_out == true
    - SEPARATE_OUT_DIR is defined

- name: "Re-do out/ linking"
  file:
    src: "{{ SEPARATE_OUT_DIR }}"
    dest: "{{ SRCPATH }}/out"
    state: link
  when: 
    - clean_out is defined and clean_out == true
    - SEPARATE_OUT_DIR is defined
