---

- include_vars: ../files/secrets.yml
  no_log: true

# set override defaults
- name: set default overrides
  set_fact:
    override_clean_basic: "false"
  when: override_clean_basic != "true" and override_clean_basic != "false"

- set_fact:
    override_clean_out: "false"
  when: override_clean_out != "true" 

- set_fact:
    override_reset_git: "false"
  when: override_reset_git == ""

- set_fact:
    override_release_build: "false"
  when: override_release_build == ""
