---

- include_vars: ../files/secrets.yml
  no_log: true

# set override defaults
- fail:
    msg: "override_clean_basic: >{{ override_clean_basic }}<"
  when: override_clean_basic is defined

- set_fact:
    override_clean_out: "false"
  when: override_clean_out == ""

- set_fact:
    override_reset_git: "false"
  when: override_reset_git == ""

- set_fact:
    override_release_build: "false"
  when: override_release_build == ""
