---

- include_vars: ../files/secrets.yml
  no_log: true

# set override defaults
- set_fact:
    override_clean_basic: "false"
  when: override_clean_basic undefined

- set_fact:
    override_clean_out: "false"
  when: override_clean_out == ""

- set_fact:
    override_reset_git: "false"
  when: override_reset_git == ""

- set_fact:
    override_release_build: "false"
  when: override_release_build == ""
