---

- block:
  - name: "Ensure no compat bin links exist"
    file:
      path: "{{ item }}"
      state: absent
    loop:
      - "~/.local/bin/python"
      - "~/.local/bin/gcc"
    when: android_shortversion != "a9"

  - name: "Ensure compat bin links exist"
    file:
      src: "{{ item.target }}"
      path: "{{ item.lname }}"
      state: link
    loop:
      - { lname: "~/.local/bin/python", target: "/usr/bin/python2" }
      - { lname: "~/.local/bin/gcc", target: "/usr/bin/gcc-9"  }
    when: android_shortversion == "a9"

  when: android_shortversion is defined

- name: Upload DOS CVE fixup
  copy:
    src: "cve_fixup/{{ target_model }}.patch"
    dest: cve_fixup.patch
    mode: 0640
  when: divest_unsupported_device
