---

- name: Find all manifests
  shell: |
    if [ -d "{{ SRCPATH }}/.repo/local_manifests" ];then
      find {{ SRCPATH }}/.repo/manifests/ {{ SRCPATH }}/.repo/local_manifests -name '*.xml'
    else
      find {{ SRCPATH }}/.repo/manifests/ -name '*.xml'
    fi
  args:
    executable: /bin/bash
  register: manifests
  no_log: true

- name: Parse manifests
  community.general.xml:
    path: "{{ item }}"
    xpath: /manifest/project
    content: attribute
  loop: "{{ manifests.stdout.splitlines() | map('from_yaml') }}"
  register: xmlout
  no_log: true

- name: Parse manifests (removals)
  community.general.xml:
    path: "{{ item }}"
    xpath: /manifest/remove-project
    content: attribute
  failed_when: never is defined
  loop: "{{ manifests.stdout.splitlines() | map('from_yaml') }}"
  register: xmlremovals
  no_log: true

- name: "Clean old results file"
  file:
    path: "{{ manifest_paths_file }}"
    state: absent
  no_log: true

- name: Write manifest paths file
  template:
    src: ../roles/common/templates/manifest_paths.j2
    dest: "{{ manifest_paths_file }}"

- name: "remove unwanted"
  replace:
    path: "{{ manifest_paths_file }}"
    regexp: "^{{ item.path }}$\\n"
  loop: "{{ xmlremovals.results | selectattr('matches','defined') | map(attribute='matches') | sum(start=[]) | map(attribute='remove-project') }}"

- name: "Reset path(s)"
  shell: 'cat {{ manifest_paths_file }} | parallel -j6 --max-args=10 {{ repo_bin }} forall -j1 {1} {2} {3} {4} {5} {6} {7} {8} {9} {10} -c "git reset --hard"'
  args:
    chdir: "{{ SRCPATH }}"
    executable: /bin/bash
  register: resetres
  failed_when: 
    - resetres.rc != 14   # skipped only
    - resetres.rc != 16   # skipped+
    - resetres.rc != 17   # skipped+
    - resetres.rc != 21   # local path missing
    - resetres.rc != 22   # skipped+
    - resetres.rc != 23   # skipped+
    - resetres.rc != 26   # project not found
    - resetres.rc != 32   # skipped?
    - resetres.rc != 58   # project not found
    - resetres.rc != 0    # any other error code
  #no_log: true
