---

- name: "Ensure keys dir is set correctly"
  shell: "KEYS_DIR='{{ keysdir }}' external/buildtools/sign/sign_set_keysdir.sh {{ ROM_FLAVOR | regex_replace('e-os','eos') }} {{ android_shortversion }}"
  args:
    chdir: "{{ SRCPATH }}"
  when: sign_build is defined and sign_build == "true"
