---

- block:

  - name: "create directory if needed (i.e when using sub dirs in SRC_KEYSDIR)"
    file:
      path: "{{ SRC_KEYSDIR_BASE }}"
      state: directory
    when: SRC_KEYSDIR_BASE is defined
  
  - name: "Ensure keys dir is set correctly"
    shell: "external/buildtools/sign/sign_set_keysdir.sh {{ ROM_FLAVOR | regex_replace('e-os','eos') }} {{ android_shortversion }}"
    args:
      chdir: "{{ SRCPATH }}"
    environment:
      KEYS_DIR: "{{ keysdir }}"
      KEYS_DIR_LINKNAME: "{{ SRC_KEYSDIR }}"

  - fail:
    msg: booooo

  - name: "Ensure we actually have keys (i.e. generate them if needed)"
    shell: external/buildtools/sign/sign_generate_keys.sh
    args:
      chdir: "{{ SRCPATH }}"
      executable: /bin/bash
    environment:
      CERT_CN: "{{ KEYS_CN }}"
      KEYS_DIR: "{{ SRC_KEYSDIR }}"
      USER_NAME: "{{ KEYS_USER }}"
      KSIZE: "{{ KEYS_SIZE }}"
      HASHTYPE: "{{ KEYS_HASHTYPE }}"

  when: sign_build is defined and sign_build == "true"
