---

- name: "Get local manifests (if set)"
  git:
    repo: "{{ git_repo_local_manifests }}"
    dest: "{{ SRCPATH }}/.repo/local_manifests"
    version: "{{ git_repo_local_manifests_branch }}"
    force: true
  when: git_repo_local_manifests is defined

- name: "Init Android sources"
  shell: "{{ repo_bin }} init -u {{ git_repo_main_manifests }} -b {{ git_repo_main_branch | d(REPOBRANCH) }}"
  args:
    chdir: "{{ SRCPATH }}"

- name: "Sync"
  shell: "{{ repo_bin }} sync -c -j{{ max_processes }} --force-sync --no-tags --no-clone-bundle"
  args:
    chdir: "{{ SRCPATH }}"
  no_log: true

- name: "Sync LFS"
  shell: "{{ repo_bin }} forall -j{{ max_processes }} -c 'git lfs pull'"
  args:
    chdir: "{{ SRCPATH }}"
  ignore_errors: yes
  when: ROM_FLAVOR == 'eos' or (sync_lfs is defined and sync_lfs == 'true')
  no_log: true

- name: "Ensure keys dir is set correctly"
  shell: "KEYS_DIR='{{ SRC_KEYSDIR }}' external/buildtools/sign/sign_set_keysdir.sh {{ ROM_FLAVOR | regex_replace('e-os','eos') }} {{ android_shortversion }}"
  args:
    chdir: "{{ SRCPATH }}"
  when: sign_build is defined and sign_build == "true"
  
