---

tg_success: |
        {{ ICON_GOOD }} ***New build has finished\!***
        
        {{ device_cl }}
        Build ID: {{ build_id | replace(".","\.") }}
        {% if release_channel is defined %}
        Release channel: {{ release_channel | regex_escape() }}
        {% endif %}
        {% if ROM_TYPE is defined %}
        Release type: {{ ROM_TYPE | regex_escape() }}
        {% endif %}
        {% if sec_level_date.stdout is defined %}
        ***Platform security patch level:*** [{{ sec_level_date.stdout | regex_escape() }}](https://source.android.com/docs/security/bulletin/{{ sec_level_date.stdout | regex_replace('([0-9]+-[0-9]+)(-[0-9]+)','\1-01' ) }})
        {% endif %}
        
        {{ rom_cl }}
        {{ kernel_cl }}
        {{ dtree_cl }}
        {% if cdtree_cl is defined %}
        {{ cdtree_cl }}
        {% endif %}
        
        {{ dl_links }}
        {% if ota_hint is defined %}
        {{ ota_hint | replace("!","\!") | replace("-","\-")  | replace(".","\.") | replace(">","\>") }}
        {% endif %}
        
        ***SHA256:***
        {{ hash.stat.checksum | default("no hash found") }}
        
        This build has been created by my [Ansible project](https://github.com/sfX-android/automation_scripts) \+ [Semaphore](https://ansible-semaphore.com) with ❤️

tg_failed: |
        {{ ICON_BAD }} ***ERROR:*** Last build failed\!
        \- ROM: {{ ROM_FLAVOR | replace("-","\-") }} {{ android_shortversion | replace("-","\-") | replace(".","\.") }}
        \- Device: ***{{ BDEVICE | replace("-","\-") }}***
        \- Build ident: _{{ BUILDIDENT | replace("-","\-") }}_
        \- Build ID:  {{ build_id | regex_escape() }}
        {% if release_channel is defined %}
        \- Release channel: {{ release_channel | regex_escape() }}
        {% endif %}
        {% if ROM_TYPE is defined %}
        \- Release type: {{ ROM_TYPE | regex_escape() }}
        {% endif %}
