---

- name: "get ansible log path"
  connection: local
  shell: >-
    grep -E '^log_path\s+=' "{{ ansible_config_file }}" | cut -d '=' -f 2
  register: ansible_log

- set_fact:
    ansible_log_flatten: "{{ ansible_log.stdout | regex_replace('\\$HOME', ansible_home_dir) }}"

- name: rotate ansible log
  connection: local
  shell: "mv {{ ansible_log_flatten }} {{ ansible_log_flatten }}.{{ build_no }}"

- block:

  - stat:
      path: "/tmp/{{ inventory_hostname }}/{{ build_log_name }}"
    register: buildlogfile
    connection: local
  
  - name: rotate build log
    connection: local
    shell: "mv /tmp/{{ inventory_hostname }}/{{ build_log_name }} /tmp/{{ inventory_hostname }}/build_{{ target_model }}_{{ android_shortversion }}_{{ ROM_FLAVOR }}.log.{{ build_no }}"
    when: buildlogfile.stat.isreg is defined

  when: ROM_FLAVOR != "MAID"
