---

- name: "Apply bionic patch (cam fix)"
  shell: "patch -p1 < ../external/patches/platform_bionic.patch && touch .tmp/bionic.patched"
  args:
    chdir: "{{ SRCPATH }}/bionic"
  creates: ".tmp/bionic.patched"

- name: "Apply art patch (memfd fix)"
  shell: "patch -p1 < ../external/patches/android_art.patch && touch .tmp/art.patched"
  args:
    chdir: "{{ SRCPATH }}/art"
  creates: ".tmp/art.patched"

- name: "Patch vendor (keys)"
  shell: "/home/androidsource/buildtools/sign/sign_set_keysdir.sh {{ ROM_FLAVOR }} 10 && touch .tmp/vendor.patched"
  args:
    chdir: "{{ SRCPATH }}"
  creates: ".tmp/vendor.patched"
