---
# human readable model name
target_model_full: "Sony Xperia XZ2 Compact"

# boot debugger path & config
extendrom_debug_path_default: /metadata
extendrom_debug_path_size_full_default: 500 
extendrom_debug_path_size_kernel_default: 100
extendrom_debug_path_size_selinux_default: 200
extendrom_debug_path_size_crash_default: 200

# path to the kernel dir (req for e.g. wireguard)
target_kernel_dir: kernel/sony/sdm845

# upload the recovery image
axp_release_recovery: True

dtree_cl: |-
  \- device tree: [commits](https://github.com/AXP-OS/android_device_sony_xz2c/commits/{{ build_tag }})

cdtree_cl: |-
  \- common tree: [commits](https://github.com/AXP-OS/android_device_sony_tama-common/commits/{{ build_tag }})

kernel_cl: |-
  \- Kernel: [commits](https://github.com/AXP-OS/android_kernel_sony_sdm845/commits/{{ build_tag }})
