---

# build vars
SRCPATH: "/home/androidsource/do-not-touch/shrp"
PREFIXFNAME: "SHRP"
SEPARATE_OUT_DIR: "/ssd/{{ PREFIXFNAME }}/{{ BDEVICE }}/out"
rempath: "/home/nightlies/roms/{{ ROM_FLAVOR }}/{{ target_model }}/"

# manifests
git_repo_main_manifests: "git@github.com:SHRP/manifest.git"

# notification vars
rom_cl: |-
  ***Changes:***
  \- SHRP: [Changelog](https://shrp.github.io/#/changelogs)

dl_links: |-
  ***Download:*** [{{ ROMFILE.stdout | replace("-","\-") | replace(".","\.") }}]({{ leech_server }}/{{ ROM_FLAVOR }}/{{ target_model }})

#  ***Download:*** [{{ ROMFILE.stdout | replace("-","\-") | replace("_","\_") | replace(".","\.") }}]({{ leech_server }}/{{ ROM_FLAVOR }}/{{ target_model }})


