---

# build vars
PREFIXFNAME: "SHRP"
SRCPATH: "/home/androidsource/do-not-touch/{{ PREFIXFNAME }}"
SEPARATE_OUT_DIR: "/ssd/{{ PREFIXFNAME }}/{{ BDEVICE }}/out"
rempath: "/home/nightlies/roms/{{ ROM_FLAVOR }}/{{ target_model }}/"

# manifests
git_repo_main_manifests: "git@github.com:SHRP/manifest.git"

# notification vars
rom_cl: |-
  ***Changes:***
  \- SHRP: [Changelog](https://shrp.github.io/#/changelogs)

dl_links: |-
  ***Download:*** [{{ ROMFILE.stdout | replace("-","\-") | replace("_","\_") | replace(".","\.") }}]({{ leech_server }}/{{ ROM_FLAVOR }}/{{ target_model }})

device_cl: |-
  ***{{ target_model_full | replace("-","\-") }}*** ***\({{ target_model | replace("-","\-") | replace("_","\_") }}\)*** \- ***{{ ROM_FLAVOR | replace("-","\-") }} {{ git_repo_main_branch | replace("-","\-") | replace("_","\_") | replace(".","\.") }}***

kernel_cl: |-
  \- Kernel: [commits]({{ KERNGIT | replace('.git','') }}/commits/{{ KERNBRANCH }})

dtree_cl: |-
  \- Device tree: [commits]({{ DTURI | replace('.git','') }}/commits/{{ DTBRANCH }})
